-- Food & Market complete official printed catalogue (Unicode source).
-- Generated by scripts/generate-food-market-catalogue.mjs; review-first and rollback-only.
BEGIN;

DO $$
DECLARE actual_3d integer;
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.restaurants r JOIN public.brands b ON b.id = r.brand_id WHERE r.id = 73 AND r.slug = 'food-market-main' AND r.brand_id = 67 AND b.id = 67 AND b.slug = 'food-market' AND b.name = 'Food & Market') THEN
    RAISE EXCEPTION 'Food & Market identity assertion failed';
  END IF;
  SELECT count(*) INTO actual_3d FROM public.menu_items WHERE restaurant_id = 73 AND is_3d IS TRUE;
  IF actual_3d <> 3 OR EXISTS (
    SELECT 1 FROM (VALUES
      (1383, 'Burrata Salad', 'BURRATA SALAD'),
      (1385, 'Chicken Balls in Shkmeruli Sauce', 'CHICKEN BALLS IN SHKMERULI SAUCE'),
      (1421, 'Unagi Philadelphia', 'Unagi Philadelphia')
    ) expected(id, live_name_en, official_name_en)
    LEFT JOIN public.menu_items m ON m.restaurant_id = 73 AND m.id = expected.id
    WHERE m.id IS NULL OR (m.name_en IS DISTINCT FROM expected.live_name_en AND m.name_en IS DISTINCT FROM expected.official_name_en)
      OR COALESCE(m.model, '') = '' OR COALESCE(m.model_usdz, '') = '' OR m.is_3d IS NOT TRUE
  ) THEN RAISE EXCEPTION 'Food & Market 3D preservation assertion failed'; END IF;
END $$;

CREATE TEMP TABLE _fm_preserved AS
SELECT id, model, model_usdz, thumbnail_url, ar_scale, is_3d, thumb_3d
FROM public.menu_items WHERE restaurant_id = 73 AND id IN (1383, 1385, 1421);

CREATE TEMP TABLE _fm_categories (restaurant_id bigint, name_en text, name_ka text, name_ru text, sort_order integer) ON COMMIT DROP;
INSERT INTO _fm_categories VALUES
  (73, 'Georgian — Pizza', 'ქართული — პიცა', NULL, 1),
  (73, 'Georgian — Burger', 'ქართული — ბურგერი', NULL, 2),
  (73, 'Georgian — Pasta', 'ქართული — პასტა', NULL, 3),
  (73, 'Georgian — Appetizer', 'ქართული — აპეტაიზერი', NULL, 4),
  (73, 'Georgian — Salads', 'ქართული — სალათები', NULL, 5),
  (73, 'Georgian — Soups', 'ქართული — წვნიანი', NULL, 6),
  (73, 'Georgian — Croquettes', 'ქართული — კროკეტები', NULL, 7),
  (73, 'Georgian — Dough', 'ქართული — ცომეული', NULL, 8),
  (73, 'Georgian — Main', 'ქართული — ძირითადი', NULL, 9),
  (73, 'Thai — Stir Fried', 'ტაილანდური — სთირ ფრაიდ', NULL, 10),
  (73, 'Thai — Fried Rice', 'ტაილანდური — ბრინჯი', NULL, 11),
  (73, 'Thai — Salads', 'ტაილანდური — სალათები', NULL, 12),
  (73, 'Thai — Appetizer', 'ტაილანდური — აპეტაიზერი', NULL, 13),
  (73, 'Thai — Curry', 'ტაილანდური — ქარი', NULL, 14),
  (73, 'Thai — Noodles', 'ტაილანდური — ნუდლსი', NULL, 15),
  (73, 'Thai — Soup', 'ტაილანდური — წვნიანი', NULL, 16),
  (73, 'Japanese — Sashimi', 'იაპონური — საშიმი', NULL, 17),
  (73, 'Japanese — Nigiri', 'იაპონური — ნიგირი', NULL, 18),
  (73, 'Japanese — Onigiri', 'იაპონური — ონიგირი', NULL, 19),
  (73, 'Japanese — Maki', 'იაპონური — მაკი', NULL, 20),
  (73, 'Japanese — Uramaki Roll', 'იაპონური — ურამაკი როლი', NULL, 21),
  (73, 'Japanese — Futomaki', 'იაპონური — ფუტომაკი', NULL, 22),
  (73, 'Japanese — Poke Bowl', 'იაპონური — თასი', NULL, 23),
  (73, 'Drinks — White Classic', 'სასმელები — თეთრი კლასიკური', NULL, 24),
  (73, 'Drinks — White Dry Qvevri', 'სასმელები — თეთრი მშრალი ქვევრის', NULL, 25),
  (73, 'Drinks — White Semi Sweet', 'სასმელები — თეთრი ნახევრად ტკბილი', NULL, 26),
  (73, 'Drinks — Red Dry Classic', 'სასმელები — წითელი მშრალი კლასიკური', NULL, 27),
  (73, 'Drinks — Red Dry Qvevri', 'სასმელები — წითელი მშრალი ქვევრის', NULL, 28),
  (73, 'Drinks — Red Semi Sweet', 'სასმელები — წითელი ნახევრად ტკბილი', NULL, 29),
  (73, 'Drinks — Rose', 'სასმელები — ვარდისფერი', NULL, 30),
  (73, 'Drinks — Sparkling Wine', 'სასმელები — ცქრიალა ღვინო', NULL, 31),
  (73, 'Drinks — Wine by the Glass', 'სასმელები — ჭიქით', NULL, 32),
  (73, 'Drinks — Refreshing Beverages', 'სასმელები — გამაგრილებელი სასმელი', NULL, 33),
  (73, 'Drinks — Coffee & Tea', 'სასმელები — ყავა და ჩაი', NULL, 34),
  (73, 'Drinks — Beer', 'სასმელები — ლუდი', NULL, 35),
  (73, 'Drinks — Vodka', 'სასმელები — არაყი', NULL, 36),
  (73, 'Drinks — Chacha', 'სასმელები — ჭაჭა', NULL, 37),
  (73, 'Drinks — Gin', 'სასმელები — ჯინი', NULL, 38),
  (73, 'Drinks — Tequila', 'სასმელები — ტეკილა', NULL, 39),
  (73, 'Drinks — Vermouth and Bitters', 'სასმელები — ვერმუტი და ბიტერი', NULL, 40),
  (73, 'Drinks — Rum & Liquor', 'სასმელები — რომი და ლიქიორი', NULL, 41),
  (73, 'Drinks — Whiskey', 'სასმელები — ვისკი', NULL, 42),
  (73, 'Drinks — Brandy and Cognac', 'სასმელები — ბრენდი და კონიაკი', NULL, 43),
  (73, 'Drinks — Cocktail', 'სასმელები — კოქტეილი', NULL, 44);

INSERT INTO public.categories (restaurant_id, name_en, name_ka, name_ru, sort_order)
SELECT * FROM _fm_categories
ON CONFLICT (restaurant_id, name_en) DO UPDATE SET name_ka = EXCLUDED.name_ka, name_ru = NULL, sort_order = EXCLUDED.sort_order;

CREATE TEMP TABLE _fm_items (preserved_id bigint, category_en text, menu_page text, cuisine text, name_en text, name_ka text, description_en text, description_ka text, price text, thumbnail_url text, variants jsonb, sort_order integer, source_pdf text, source_page integer) ON COMMIT DROP;
INSERT INTO _fm_items VALUES
  (200001, 'Georgian — Pizza', 'georgian', NULL, 'MARGHERITA', 'მარგარიტა', 'Tomato sauce, Mozzarella
Milk Product, Gluten', 'ტომატის სოუსი, მოცარელა
რძის ნაწარმი, გლუტენი', '24.00 ₾', '', '[]'::jsonb, 1, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 1),
  (200002, 'Georgian — Pizza', 'georgian', NULL, 'PEPPERONI', 'პეპერონი', 'Tomato sauce, Mozzarella, Pepperoni
Milk Product, Gluten', 'ტომატის სოუსი, მოცარელა, პეპერონი
რძის ნაწარმი, გლუტენი', '33.00 ₾', '', '[]'::jsonb, 2, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 1),
  (200003, 'Georgian — Pizza', 'georgian', NULL, '4 CHEESE', '4 ყველი', 'Edamer, Gauda, Gorgonzola, Mozzarella
Milk Product, Gluten', 'ედამერი, გაუდა, გორგონზოლა, მოცარელა
რძის ნაწარმი, გლუტენი', '34.00 ₾', '', '[]'::jsonb, 3, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 1),
  (200004, 'Georgian — Pizza', 'georgian', NULL, 'PROSCIUTTO', 'პროშუტო', 'Prosciutto, Mushrooms, Mozzarella
Milk Product, Gluten', 'პროშუტო, სოკო, მოცარელა
რძის ნაწარმი, გლუტენი', '35.00 ₾', '', '[]'::jsonb, 4, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 1),
  (200005, 'Georgian — Pizza', 'georgian', NULL, 'CHEF’S PIZZA', 'შეფ პიცა', 'Cream, Ham, Mushrooms, Mozzarella
Milk Product, Gluten', 'ნაღები, ლორი, სოკო, მოცარელა
რძის ნაწარმი, გლუტენი', '32.00 ₾', '', '[]'::jsonb, 5, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 1),
  (200006, 'Georgian — Pizza', 'georgian', NULL, 'VEGETARIAN', 'ვეგეტარიანული', 'Tomato Sauce, Mozzarella, Bell Pepper Green and Red, Mushrooms, Cherry Tomatoes, Black Olives
Gluten', 'ტომატის სოუსი, მოცარელა, ბულგარული წითელი და მწვანე, სოკო, პომიდორი ჩერი, შავი ზეთისხილი
გლუტენი', '24.00 ₾', '', '[]'::jsonb, 6, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 1),
  (200007, 'Georgian — Pizza', 'georgian', NULL, 'BLACK TRUFFLE PIZZA', 'შავი ტრუფელის პიცა', 'Cream, Mozzarella, Parmesan, Mushroom, Truffle Pasta', 'ნაღები, მოცარელა, პარმეზანი, სოკო, ტრუფელის პასტა', '30.00 ₾', '', '[]'::jsonb, 7, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 1),
  (200008, 'Georgian — Burger', 'georgian', NULL, 'CHICKEN BURGER', 'ბურგერი ქათმით', 'F&M Burger Bread, Chicken cutlet, Cheddar, Lettuce, Mustard, Mayo, Red Onion, Ketchup
Gluten, Milk Product, Egg, Shirbakht Seed, Fish, Mustard', 'ფუდ & მარკეტის ბურგერის პური, ქათმის კატლეტი, ჩედარი, სალათის ფოთოლი, მდოგვი, მაიონეზი, წითელი ხახვი, კეტჩუპი
გლუტენი, რძის ნაწარმი, კვერცხი, შირბახტის თესლი, თევზი, მდოგვი', '28.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-burger-chicken-burger-6a9e4fa4.webp', '[]'::jsonb, 8, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 1),
  (200009, 'Georgian — Burger', 'georgian', NULL, 'CHEF BURGER', 'შეფ ბურგერი', 'F&M Burger Bread, Cheddar cheese, Angus Meat, Jalepenio, Cheese Sauce, Marinated Cucumber, Lettuce, Tomato, Bacon
Gluten, Milk Product, Egg, Shirbakht Seed', 'ფუდ & მარკეტის ბურგერის პური, ყველი ჩედარი, ანგუსის ხორცი, ჰალეპენიო, ყველის სოუსი, კიტრის მარინადი, სალათის ფოთოლი, პომიდორი, ბეკონი
გლუტენი, რძის ნაწარმი, კვერცხი, შირბახტის თესლი', '38.00 ₾', '', '[]'::jsonb, 9, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 1),
  (200010, 'Georgian — Burger', 'georgian', NULL, 'SMASHED BURGER', 'სმეშ ბურგერი', 'F&M Burger Bread, Angus Meat, Cheddar Cheese, Salad Iceberg, Onion, Tomato, Bacon, Jalapeno Pickled
Gluten, Milk Product, Egg, Shirbakht Seed', 'ფუდ & მარკეტის ბურგერის პური, ანგუსის ხორცი, ყველი ჩედარი, აისბერგი, ხახვი, პომიდორი, ბეკონი, ჰალაპენიო
გლუტენი, რძის ნაწარმი, კვერცხი, შირბახტის თესლი', '36.00 ₾', '', '[]'::jsonb, 10, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 1),
  (200011, 'Georgian — Burger', 'georgian', NULL, 'STEAK SANDWICH', 'სტეიკ სენდვიჩი', 'F&M Tonis Puri, Angus Meat, Iceberg lettuce, Tomato, Mustard, Mayonnaise, Onion, Gherkins, Cheddar Cheese
Gluten, Milk Product, Egg, Shirbakht Seed, Mustard', 'ფუდ ენდ მარკეტის თონის პური, საქონლის ხორცის სტეიკი, აისბერგი, პამიდორი, მდოგვი, მაიონეზი, ხახვი, კიტრის მარინადი, ყველი ჩედარი
გლუტენი, რძის ნაწარმი, კვერცხი, შირბახტის თესლი, მდოგვი', '40.00 ₾', '', '[]'::jsonb, 11, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 1),
  (200012, 'Georgian — Pasta', 'georgian', NULL, 'SALMON PASTA', 'ორაგულის პასტა', 'Salmon, Garlic, Cream, Parmesan, Coriander, Olive Oil
Gluten, Seafood, Milk Product, Egg', 'ორაგული, ნიორი, ნაღები, პარმეზანი, ქინძი, ზეითუნის ზეთი
გლუტენი, ზღვის პროდუქტი, რძის ნაწარმი, კვერცხი', '34.00 ₾', '', '[]'::jsonb, 12, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 1),
  (200013, 'Georgian — Pasta', 'georgian', NULL, 'PENNE ARRABIATA', 'პენე არაბიატა', 'Tomato sauce, Cherry Tomatoes, Parmesan, Parsley, Spring Onion
Gluten, Soy, Milk Product, Egg', 'პომიდვრის სოუსი, პომიდორი ჩერი, პარმეზანი, ოხრახუში, მწვანე ხახვი
გლუტენი, სოია, რძის ნაწარმი, კვერცხი', '23.00 ₾', '', '[]'::jsonb, 13, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 1),
  (200014, 'Georgian — Pasta', 'georgian', NULL, 'PENNE BOLOGNESE', 'პენე ბოლონეზე', 'Meat, Parmesan, Parsley, Spring Onion
Gluten, Soy, Milk Product, Egg', 'ხორცი, პარმეზანი, ოხრახუში, მწვანე ხახვი
გლუტენი, სოია, რძის ნაწარმი, კვერცხი', '30.00 ₾', '', '[]'::jsonb, 14, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 1),
  (200015, 'Georgian — Pasta', 'georgian', NULL, 'SPAGHETTI CARBONARA', 'სპაგეტი კარბონარა', 'Eggs, Cream, Bacon, Parmesan, Parsley, Spring Onion, Garlic
Gluten, Soy, Milk Product, Egg', 'კვერცხი, ნაღები, ბეკონი, პარმეზანი, ოხრახუში, მწვანე ხახვი, ნიორი
გლუტენი, სოია, რძის ნაწარმი, კვერცხი', '31.00 ₾', '', '[]'::jsonb, 15, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 1),
  (200016, 'Georgian — Pasta', 'georgian', NULL, 'MUSHROOM & TRUFFLE FUSILLONI', 'სოკოს და ტრუფელის პასტა', 'Oyster Mushroom, Button Mushroom, Onion, Garlic, Cream, Truffle Pasta
Gluten, Soy, Milk Product, Egg', 'კალმახა სოკო, ქამა სოკო, ხახვი, ნიორი, ნაღები, ტრუფელის პასტა
გლუტენი, სოია, რძის ნაწარმი, კვერცხი', '29.00 ₾', '', '[]'::jsonb, 16, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 1),
  (200017, 'Georgian — Appetizer', 'georgian', NULL, 'DIP MIXES', 'დიფების მიქსი', 'Nadughi with truffle, avocado salsa, tomato salsa, tortilla chips', 'ნადუღი ტრუფელით, ავოკადოს სალსა, პომიდვრის სალსა, ტორტილიას ჩიფსები', '20.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-appetizer-dip-mixes-98a7b175.webp', '[]'::jsonb, 17, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200018, 'Georgian — Appetizer', 'georgian', NULL, 'PULLED BBQ PORK TACO', 'ტაკო ღორის ხორცით და მანგოს სალსათი', 'GLUTEN', 'გლუტენი', '27.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-appetizer-pulled-bbq-pork-taco-2288c30e.webp', '[]'::jsonb, 18, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200019, 'Georgian — Appetizer', 'georgian', NULL, 'PULLED BEEF TACO', 'ტაკო საქონლის ხორცით და კივის სალსათი', 'GLUTEN', 'გლუტენი', '28.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-appetizer-pulled-beef-taco-ba94bfb6.webp', '[]'::jsonb, 19, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200020, 'Georgian — Appetizer', 'georgian', NULL, 'HUMMUS WITH GREEN SALAD AND PITA', 'ჰუმუსი მწვანე სალათით და პიტა პურით', NULL, NULL, '27.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-appetizer-hummus-with-green-salad-and-pita-9f260f56.webp', '[]'::jsonb, 20, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200021, 'Georgian — Appetizer', 'georgian', NULL, 'FRENCH FRIES WITH TRUFFLE SAUCE', 'კარტოფილი ფრი ტრუფელის სოუსით', NULL, NULL, '14.00 ₾', '', '[]'::jsonb, 21, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200022, 'Georgian — Appetizer', 'georgian', NULL, 'FRENCH FRIES', 'კარტოფილი ფრი', NULL, NULL, '10.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-appetizer-french-fries-522e1f87.webp', '[]'::jsonb, 22, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200023, 'Georgian — Salads', 'georgian', NULL, 'CAESAR SALAD with CHICKEN', 'სალათი ცეზარი ქათმით', 'Fish, Milk Product, Mustard, Gluten, Egg, Bacon', 'ანჩოუსი, რძის ნაწარმი, მდოგვი, გლუტენი, კვერცხი, ბეკონი', '28.00 ₾', '', '[]'::jsonb, 23, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (1383, 'Georgian — Salads', 'georgian', NULL, 'BURRATA SALAD', 'ბურატას სალათი', NULL, NULL, '34.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/items/burrata-salad.webp', '[]'::jsonb, 24, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200025, 'Georgian — Salads', 'georgian', NULL, 'Kakhetian Cucumber & Tomato salad', 'კიტრი პომიდვრის სალათი კახურად', NULL, NULL, '20.00 ₾', '', '[]'::jsonb, 25, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200026, 'Georgian — Salads', 'georgian', NULL, 'Cucumber & Tomato salad with Walnut', 'კიტრი პომიდვრის სალათი ნიგვზით', NULL, NULL, '22.00 ₾', '', '[]'::jsonb, 26, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200027, 'Georgian — Salads', 'georgian', NULL, 'SHRIMP SALAD', 'კრევეტის სალათი', NULL, NULL, '32.00 ₾', '', '[]'::jsonb, 27, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200028, 'Georgian — Soups', 'georgian', NULL, 'BEEF SOUP, RICE NOODLES', 'საქონლის ხორცის წვნიანი ბრინჯის ნუდლსით', NULL, NULL, '29.00 ₾', '', '[]'::jsonb, 28, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200029, 'Georgian — Soups', 'georgian', NULL, 'CHIKHIRTMA WITH SMOKED SULGUNI', 'ჩიხირთმა შებოლილი სულგუნით', 'Milk Product, Egg', 'რძის ნაწარმი, კვერცხი', '26.00 ₾', '', '[]'::jsonb, 29, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200030, 'Georgian — Soups', 'georgian', NULL, '3 MUSHROOMS CREAM SOUP', 'სამი სოკოს შეჭამანდი', 'Milk Product', 'რძის ნაწარმი', '24.00 ₾', '', '[]'::jsonb, 30, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200031, 'Georgian — Soups', 'georgian', NULL, 'PUMPKIN CREAM SOUP, CROSTINI', 'გოგრის კრემ-სუპი', 'Milk Product', 'რძის ნაწარმი', '18.00 ₾', '', '[]'::jsonb, 31, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200032, 'Georgian — Croquettes', 'georgian', NULL, 'CHICKEN STICKS WITH SESAME', 'ქათმის ჩხირები სეზამით', NULL, NULL, '28.00 ₾', '', '[]'::jsonb, 32, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200033, 'Georgian — Croquettes', 'georgian', NULL, 'CHEESE STICKS IN TOMATO SAUCE', 'ყველის ჩხირები პომიდვრის სოუსში', NULL, NULL, '27.00 ₾', '', '[]'::jsonb, 33, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200034, 'Georgian — Croquettes', 'georgian', NULL, 'LOBIO BALLS WITH HAM IN JONJOLI SAUCE', 'ლობიოს ბურთები ლორით ჯონჯოლის სოუსში', NULL, NULL, '27.00 ₾', '', '[]'::jsonb, 34, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (1385, 'Georgian — Croquettes', 'georgian', NULL, 'CHICKEN BALLS IN SHKMERULI SAUCE', 'ქათმის ბურთები შქმერულ სოუსში', NULL, NULL, '27.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/items/chicken-balls.webp', '[]'::jsonb, 35, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200036, 'Georgian — Croquettes', 'georgian', NULL, 'ELARJI BALLS WITH KUPATI IN BAJHE SAUCE', 'ელარჯის ბურთები კუპატის შიგთავსით ბაჟეს სოუსში', NULL, NULL, '27.00 ₾', '', '[]'::jsonb, 36, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200037, 'Georgian — Dough', 'georgian', NULL, 'IMERETIAN KHACHAPURI', 'იმერული ხაჭაპური', 'Gluten, Milk Product, Egg', 'გლუტენი, რძის ნაწარმი, კვერცხი', '28.00 ₾', '', '[]'::jsonb, 37, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200038, 'Georgian — Dough', 'georgian', NULL, 'ADJARIAN KHACHAPURI', 'აჭარული ხაჭაპური', 'Gluten, Milk Product, Egg', 'გლუტენი, რძის ნაწარმი, კვერცხი', '27.00 ₾', '', '[]'::jsonb, 38, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200039, 'Georgian — Dough', 'georgian', NULL, 'MEGRELIAN KHACHAPURI', 'მეგრული ხაჭაპური', 'Gluten, Milk Product, Egg', 'გლუტენი, რძის ნაწარმი, კვერცხი', '30.00 ₾', '', '[]'::jsonb, 39, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200040, 'Georgian — Main', 'georgian', NULL, 'CHICKEN SCHNITZEL', 'ქათმის შნიცელი', NULL, NULL, '28.00 ₾', '', '[]'::jsonb, 40, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200041, 'Georgian — Main', 'georgian', NULL, 'SALMON WITH SPINACH', 'ორაგული ისპანახით', NULL, NULL, '52.00 ₾', '', '[]'::jsonb, 41, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200042, 'Georgian — Main', 'georgian', NULL, 'GRILLED LEMON CHICKEN, PARMESAN, SUN DRIED TOMATO', 'გრილზე შემწვარი ქათმის ფილე', 'Milk Product', 'ლიმონით, პარმეზანით და მზეზე გამომშრალი პომიდორით
რძის ნაწარმი', '30.00 ₾', '', '[]'::jsonb, 42, 'FM GEORGIAN 2026 MAY 31x46cm.pdf', 2),
  (200043, 'Thai — Stir Fried', 'asian', 'thai', 'Stir Fried Cashewnut', 'სთირ ფრაიდ ქეშიუ', 'Cashewnut, Fish Sauce, Oyster Sauce', 'ქეშიუ, თევზის სოუსი, ხამანწკის სოუსი', '32.00 ₾', '', '[{"en":"Chicken","ka":"ქათამი","price":"32.00 ₾"},{"en":"Shrimp","ka":"კრევეტი","price":"38.00 ₾"}]'::jsonb, 43, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200044, 'Thai — Stir Fried', 'asian', 'thai', 'Stir Fried Broccoli with Shrimp', 'სთირ ფრაიდ ბროკოლი კრევეტით', 'Soy sauce, Oyster sauce', 'სოიოს სოუსი, ხამანწკის სოუსი', '36.00 ₾', '', '[]'::jsonb, 44, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200045, 'Thai — Fried Rice', 'asian', 'thai', 'Thai Style Fried Rice', 'ბრინჯი აზიურად', 'Soy Sauce', 'სოიოს სოუსი', '18.00 ₾', '', '[{"en":"Veggie","ka":"ბოსტნეული","price":"18.00 ₾"},{"en":"Chicken","ka":"ქათამი","price":"25.00 ₾"},{"en":"Shrimp","ka":"კრევეტი","price":"34.00 ₾"}]'::jsonb, 45, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200046, 'Thai — Fried Rice', 'asian', 'thai', 'Sriracha Fried Rice', 'სრირაჩა ფრაიდ რაის', 'Soy sauce, White Sesame seed', 'სოიოს სოუსი, სეზამის მარცვალი', '27.00 ₾', '', '[{"en":"Chicken","ka":"ქათამი","price":"27.00 ₾"},{"en":"Shrimp","ka":"კრევეტი","price":"36.00 ₾"}]'::jsonb, 46, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200047, 'Thai — Fried Rice', 'asian', 'thai', 'Chicken Donburi', 'დონბური ქათმით', 'Sesame Oil, White Sesame Seed, Soy Sauce, Oyster sauce', 'სეზამის ზეთი, სეზამის მარცვალი, სოიოს სოუსი, ხამანწკის სოუსი', '20.00 ₾', '', '[]'::jsonb, 47, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200048, 'Thai — Fried Rice', 'asian', 'thai', 'Rice with Grilled Chicken & Satay Sauce', 'ბრინჯი ქათმით და მიწისთხილის სოუსით', 'Coconut Milk, Dark Soy sauce, Oyster sauce, Fish sauce, Peanut, White Sesame Seed', 'ქოქოსის რძე, სოიოს სოუსი, ხამანწკის სოუსი, თევზის სოუსი, მიწისთხილი, სეზამის მარცვალი', '28.00 ₾', '', '[]'::jsonb, 48, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200049, 'Thai — Fried Rice', 'asian', 'thai', 'Grilled chicken with curry rice', 'ქათამი გრილზე ქარი ბრინჯით', 'Steam Rice, Curry, Turmeric, Garlic, Shallot, Onion, Coriander, Cucumber', 'ბრინჯი, ქარი, კურკუმა, ნიორი, შალოტი, ხახვი, ქინძი, კიტრი', '29.00 ₾', '', '[]'::jsonb, 49, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200050, 'Thai — Salads', 'asian', 'thai', 'Grilled Chicken Salad', 'ქათმის სალათი გრილზე', 'Chicken, Thai Spices, Red Chili, Cherry tomato, Cucumber, Spring Onion, Onion, Shallot, Coriander, Fish sauce', 'ქათამი, ტაი სანელებლები, წითელი ჩილი, პომიდორი ჩერი, კიტრი, მწვანე ხახვი, ხახვი, შალოტი, ქინძი, თევზის სოუსი', '27.00 ₾', '', '[]'::jsonb, 50, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200051, 'Thai — Salads', 'asian', 'thai', 'Crispy Chicken Salad', 'ხრაშუნა ქათმის სალათი', 'Chicken, Spring onion, Shallot, white onion, Celery, Coriander, Tomato, Red chilli', 'ქათამი, მწვანე ხახვი, შალოტი, თეთრი ხახვი, ნიახური, ქინძი, პამიდორი, წითელი ჩილი', '27.00 ₾', '', '[]'::jsonb, 51, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200052, 'Thai — Appetizer', 'asian', 'thai', 'Crispy Shrimp with Tamarind Sauce', 'ხრაშუნა კრევეტი თამარინდ სოუსით', 'Shrimp, tempura, shallot, tamarind sauce, fish sauce, coleslaw, crispy onion, chilli, coriander', 'კრევეტები, ტემპურა, თამარინდის სოუსი, თევზის სოუსი, ხრაშუნა ხახვი, წიწაკა, ქინძი', '35.00 ₾', '', '[]'::jsonb, 52, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200053, 'Thai — Appetizer', 'asian', 'thai', 'Kimchi', 'კიმჩი', 'Chinese cabbage, Ginger, Spring onion, Carrot, Chilli powder, Shrimp paste', 'ჩინური კომბოსტო, ჯინჯერი, მწვანე ხახვი, სტაფილო, ჩილის პუდრა, კრევეტის პასტა', '15.00 ₾', '', '[]'::jsonb, 53, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200054, 'Thai — Curry', 'asian', 'thai', 'Panang Curry', 'პანანგ ქარი', 'Fish sauce, Coconut milk', 'თევზის სოუსი, ქოქოსის რძე', '27.00 ₾', '', '[{"en":"Chicken","ka":"ქათამი","price":"27.00 ₾"},{"en":"Beef","ka":"საქ. ხორცი","price":"35.00 ₾"}]'::jsonb, 54, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200055, 'Thai — Curry', 'asian', 'thai', 'Massaman Curry', 'მასამან ქარი', 'White onion, Potato, Peanut, massaman curry paste', 'ხახვი, კარტოფილი, მიწისთხილი, მასამან ქარის პასტა', '24.00 ₾', '', '[{"en":"Chicken","ka":"ქათამი","price":"24.00 ₾"},{"en":"Beef","ka":"საქ.ხორცი","price":"34.00 ₾"},{"en":"Shrimp","ka":"კრევეტი","price":"34.00 ₾"}]'::jsonb, 55, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200056, 'Thai — Curry', 'asian', 'thai', 'Grilled Chicken Red Hot Curry', 'ქათამი გრილზე წითელი ქარი', 'Chicken meat, Green pea, Zucchini, Basil, Cherry tomato, Red chilli, Red curry paste', 'ქათამი, მუხუდო, ცუკინი, ბაზილი, ჩერი პომიდორი, წითელი ჩილი, წითელი ჩილის პასტა', '32.00 ₾', '', '[]'::jsonb, 56, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200057, 'Thai — Curry', 'asian', 'thai', 'Green Curry', 'მწვანე ქარი', 'Fish sauce, Coconut milk', 'თევზის სოუსი, ქოქოსის რძე', '26.00 ₾', '', '[{"en":"Chicken","ka":"ქათამი","price":"26.00 ₾"},{"en":"Shrimp","ka":"კრევეტი","price":"35.00 ₾"},{"en":"Beef","ka":"საქ. ხორცი","price":"35.00 ₾"}]'::jsonb, 57, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200058, 'Thai — Curry', 'asian', 'thai', 'Yellow Curry', 'ყვითელი ქარი', 'Fish sauce, Coconut milk', 'თევზის სოუსი, ქოქოსის რძე', '25.00 ₾', '', '[{"en":"Chicken","ka":"ქათმით","price":"25.00 ₾"},{"en":"Beef","ka":"საქ. ხორცით","price":"35.00 ₾"}]'::jsonb, 58, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200059, 'Thai — Noodles', 'asian', 'thai', 'Stir fried Noodles Sriracha Sauce', 'სრირაჩა სთირ ფრაიდ ნუდლსი', 'Celery, Soy sauce, Oyster sauce', 'ნიახური, სოიოს სოუსი, ხამანწკის სოუსი', '26.00 ₾', '', '[{"en":"Chicken","ka":"ქათამი","price":"26.00 ₾"},{"en":"Shrimp","ka":"კრევეტი","price":"32.00 ₾"}]'::jsonb, 59, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200060, 'Thai — Noodles', 'asian', 'thai', 'Stir fried Noodles Soy Sauce', 'სთირ ფრაიდ ნუდლსი სოიოს სოუსით', 'Celery, Soy sauce, Oyster sauce', 'ნიახური, სოიოს სოუსი, ხამანწკის სოუსი', '25.00 ₾', '', '[{"en":"Chicken","ka":"ქათამი","price":"25.00 ₾"},{"en":"Shrimp","ka":"კრევეტი","price":"30.00 ₾"}]'::jsonb, 60, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200061, 'Thai — Noodles', 'asian', 'thai', 'Stir fried Glass Noodles', 'სთირ ფრაიდ გლას ნუდლსი', 'Celery, Soy sauce, Oyster sauce', 'ნიახური, სოიოს სოუსი, ხამანწკის სოუსი', '24.00 ₾', '', '[{"en":"Veggie","ka":"ბოსტნეული","price":"24.00 ₾"},{"en":"Chicken","ka":"ქათამი","price":"28.00 ₾"},{"en":"Shrimp","ka":"კრევეტი","price":"36.00 ₾"}]'::jsonb, 61, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200062, 'Thai — Noodles', 'asian', 'thai', 'Pad Si Euw', 'პად სი იუ ნუდლსი', 'Soy sauce, Oyster sauce', 'სოიოს სოუსი, ხამანწკის სოუსი', '24.00 ₾', '', '[{"en":"Veggie","ka":"ბოსტნეული","price":"24.00 ₾"},{"en":"Chicken","ka":"ქათამი","price":"30.00 ₾"},{"en":"Shrimp","ka":"კრევეტი","price":"36.00 ₾"}]'::jsonb, 62, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200063, 'Thai — Noodles', 'asian', 'thai', 'Pad Thai Noodles', 'პად ტაი ნუდლსი', 'Fish sauce, Tamarind sauce, tofu', 'თევზის სოუსი, თამარინდ სოუსი, ტოფუ', '24.00 ₾', '', '[{"en":"Veggie","ka":"ბოსტნეული","price":"24.00 ₾"},{"en":"Chicken","ka":"ქათამი","price":"30.00 ₾"},{"en":"Shrimp","ka":"კრევეტი","price":"36.00 ₾"}]'::jsonb, 63, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200064, 'Thai — Soup', 'asian', 'thai', 'Tom Yum Seafood Clear Soup', 'ტომ იამი გამჭვირვალე წვნიანი ზღვის პროდუქტებით', 'Stock, Shallot, Lemongrass, Galangal, Pickle chilli, Mussel, Squid, Shrimp, Mushroom, Sweet basil, Red chilli, MSG, Fish sauce, Lime, Lime leaves', 'ბულიონი, შალოტი, ლემონგრასი, გალანგალი, მწნილი წიწაკა, მიდიები, კალმარი, კრევეტები, სოკო, ტკბილი რეჰანი, წითელი წიწაკა, MSG, თევზის სოუსი, ლაიმი, ლაიმის ფოთლები', '38.00 ₾', '', '[]'::jsonb, 64, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200065, 'Thai — Soup', 'asian', 'thai', 'Thai Noodles Black Soup', 'ტაი ნუდლსის შავი წვნიანი', 'Cinnamon, Anise star, Garlic, Rice noodles, Coleslaw, Coriander, Green Onion, Dry shitake, White pepper powder, MSG, Soy sauce, Oyster sauce, Dark soy sauce', 'დარიჩინი, ანისულის ვარსკვლავი, ნიორი, ბრინჯის ლაფშა, კოულსლოუ, ქინძი, მწვანე ხახვი, ხმელი შიიტაკე, თეთრი წიწაკის ფხვნილი, MSG, სოიოს სოუსი, ხამანწკის სოუსი, მუქი სოიოს სოუსი', '27.00 ₾', '', '[{"en":"Chicken","ka":"ქათამი","price":"27.00 ₾"},{"en":"Beef","ka":"საქონლის ხორცი","price":"33.00 ₾"}]'::jsonb, 65, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200066, 'Thai — Soup', 'asian', 'thai', 'Thai Noodle Soup with Chicken Shreded', 'ტაი ნუდლ სუფი ქათმით', 'Peanut, garlic, soy sauce, oyster sauce', 'მიწისთხილი, ნიორი, სოიოს სოუსი, ხამანწკის სოუსი', '22.00 ₾', '', '[]'::jsonb, 66, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200067, 'Thai — Soup', 'asian', 'thai', 'Tom Yum', 'ტომ იამი', 'Fish sauce, Coconut milk', 'თევზის სოუსი, ქოქოსის რძე', '26.00 ₾', '', '[{"en":"Veggie","ka":"ბოსტნეული","price":"26.00 ₾"},{"en":"Chicken","ka":"ქათამი","price":"30.00 ₾"},{"en":"Shrimp","ka":"კრევეტი","price":"36.00 ₾"}]'::jsonb, 67, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200068, 'Thai — Soup', 'asian', 'thai', 'Tom Kha', 'ტომ კჰა', 'Fish sauce, Coconut milk', 'თევზის სოუსი, ქოქოსის რძე', '26.00 ₾', '', '[{"en":"Veggie","ka":"ბოსტნეული","price":"26.00 ₾"},{"en":"Chicken","ka":"ქათამი","price":"30.00 ₾"},{"en":"Shrimp","ka":"კრევეტი","price":"36.00 ₾"}]'::jsonb, 68, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200069, 'Thai — Soup', 'asian', 'thai', 'Tom Yum Ramen with Shrimp', 'ტომ იამის რამენი კრევეტით', 'Ramen noodles, Shrimp, wakame, Bonito, Tom yum paste, Chilli paste, Egg, White sesame seed, Spring onion, Nori, Soy sauce', 'რამენის ნუდლი, კრევეტი, ვაკამე, ბონიტო, ტომ იამის პასტა, ჩილი პასტა, კვერცხი, სეზამის თესლი, მწვანე ხახვი, ნორი, სოიოს სოუსი', '32.00 ₾', '', '[]'::jsonb, 69, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200070, 'Thai — Soup', 'asian', 'thai', 'Pho with Beef', 'პჰო საქონლის ხორცით', 'Beef, White onion, Garlic, Coriander root, Ginger, Rice noodles, Cabbage, Carrot, Basil, coriander, red chilli, Soy sauce, Oyster sauce', 'საქონლის ხორცი, ხახვი, ნიორი, ქინძის ფესვი, ჯინჯერი, ბრინჯის ნუდლი, კომბოსტო, სტაფილო, ბაზილი, ქინძი, წითელი ჩილი, სოიოს სოუსი, ხამანწკის სოუსი', '38.00 ₾', '', '[]'::jsonb, 70, 'FM ASIAN 2026 MAY 31x46cm.pdf', 1),
  (200071, 'Japanese — Sashimi', 'asian', 'japanese', 'Salmon', 'ორაგული', 'salmon, lemon zest, himalayan salt', 'ორაგული, ლიმონის ცედრა, ჰიმალაის მარილი', '36.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-sashimi-salmon-75d8714e.webp', '[]'::jsonb, 71, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200072, 'Japanese — Sashimi', 'asian', 'japanese', 'Tuna', 'თინუსი', 'tuna, green onion', 'თინუსი, მწვანე ხახვი', '25.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-sashimi-tuna-97d4da5c.webp', '[]'::jsonb, 72, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200073, 'Japanese — Nigiri', 'asian', 'japanese', 'Chef', 'შეფი', 'Salmon, rice, Spring onion', 'ორაგული, ბრინჯი, მწვანე ხახვი', '25.00 ₾', '', '[]'::jsonb, 73, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200074, 'Japanese — Nigiri', 'asian', 'japanese', 'Salmon', 'ორაგული', 'salmon, rice', 'ორაგული, ბრინჯი', '22.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-nigiri-salmon-2102b157.webp', '[]'::jsonb, 74, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200075, 'Japanese — Nigiri', 'asian', 'japanese', 'Tuna', 'თინუსი', 'tuna, spring onions, rice', 'თინუსი, მწვანე ხახვი, ბრინჯი', '20.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-nigiri-tuna-38cc91c7.webp', '[]'::jsonb, 75, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200076, 'Japanese — Onigiri', 'asian', 'japanese', 'Salmon', 'ორაგული', 'rice, salmon, cream cheese, nori, teriyaki, green onion', 'ბრინჯი, ორაგული, კრემყველი, ნორი, ტერიაკი, მწვანე ხახვი', '24.00 ₾', '', '[]'::jsonb, 76, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200077, 'Japanese — Onigiri', 'asian', 'japanese', 'Shrimp', 'კრევეტი', 'rice, crab, shrimp, tempura, mayo-mango, nori', 'ბრინჯი, კრემყველი, კრევეტი, ტემპურა, მაიო-მანგო, ნორი', '20.00 ₾', '', '[]'::jsonb, 77, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200078, 'Japanese — Maki', 'asian', 'japanese', 'Kappa Maki', 'კიტრის მაკი', 'nori, rice, cucumber', 'ნორი, ბრინჯი, კიტრი', '14.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-maki-kappa-maki-5d259973.webp', '[]'::jsonb, 78, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200079, 'Japanese — Maki', 'asian', 'japanese', 'Shake Maki', 'ორაგულის მაკი', 'nori, Salmon, Rice', 'ნორი, ორაგული, ბრინჯი', '21.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-maki-shake-maki-a4c6ea2e.webp', '[]'::jsonb, 79, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200080, 'Japanese — Maki', 'asian', 'japanese', 'Ebi Maki', 'კრევეტის მაკი', 'nori, shrimp, rice, cream-cheese', 'ნორი, კრევეტი, ბრინჯი, კრემყველი', '20.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-maki-ebi-maki-757905be.webp', '[]'::jsonb, 80, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (1421, 'Japanese — Uramaki Roll', 'asian', 'japanese', 'Unagi Philadelphia', 'უნაგი ფილადელფია', 'rice, sesame, unagi fish, avocado, salmon, unagi sauce, tobiko, cream-cheese', 'ბრინჯი, სეზამი, გველთევზა, ავოკადო, ორაგული, უნაგის სოუსი, ტობიკო, კრემყველი', '44.00 ₾', 'https://pub-b253d60df14c4c1f94bada002fa59596.r2.dev/food-market-main/1787819264838_sushi.webp', '[]'::jsonb, 81, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200082, 'Japanese — Uramaki Roll', 'asian', 'japanese', 'Crab Uramaki', 'კიბორჩხალას ურამაკი', 'rice, salmon, avocado, crab mix', 'ბრინჯი, ორაგული, ავოკადო, კრაბის მიქსი', '28.00 ₾', '', '[]'::jsonb, 82, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200083, 'Japanese — Uramaki Roll', 'asian', 'japanese', 'Unagi Crispy Roll', 'უნაგის ხრაშუნა როლი', 'rice, sesame, cream-cheese, shrimp, unagi fish, unagi sauce, mayo, panko', 'ბრინჯი, სეზამი, კრემ-ყველი, კრევეტი, გველთევზა, უნაგის სოუსი, მაიო, პანკო', '42.00 ₾', '', '[]'::jsonb, 83, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200084, 'Japanese — Uramaki Roll', 'asian', 'japanese', 'Spicy Salmon', 'ცხარე ორაგული', 'nori, rice, sesame, salmon, cucumber, spicy mayo, spring onion', 'ნორი, ბრინჯი, სეზამი, ორაგული, კიტრი, ცხარე მაიო, მწვანე ხახვი', '28.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-uramaki-roll-spicy-salmon-14f590ef.webp', '[]'::jsonb, 84, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200085, 'Japanese — Uramaki Roll', 'asian', 'japanese', 'California', 'კალიფორნია', 'nori, rice, tobiko, mayo, shrimp, crab, cucumber', 'ნორი, ბრინჯი, ტობიკო, მაიონეზი, კრევეტი, კიბორჩხალა, კიტრი', '30.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-uramaki-roll-california-aecaa463.webp', '[]'::jsonb, 85, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200086, 'Japanese — Uramaki Roll', 'asian', 'japanese', 'Dragon', 'დრაგონ', 'nori, rice, sesame, shrimp, spicy mayo, avocado, unagi fish, teriyaki sauce', 'ნორი, ბრინჯი, სეზამი, კრევეტი, ცხარე მაიონეზი, ავოკადო, გველთევზა, ტერიაკის სოუსი', '38.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-uramaki-roll-dragon-1952043b.webp', '[]'::jsonb, 86, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200087, 'Japanese — Uramaki Roll', 'asian', 'japanese', 'Spicy Tuna', 'ცხარე თინუსი', 'nori, rice, cucumber, sesame, tuna, spicy mayo, green onion', 'ნორი, ბრინჯი, კიტრი, სეზამი, თინუსი, ცხარე მაიო, მწვანე ხახვი', '25.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-uramaki-roll-spicy-tuna-9b131c51.webp', '[]'::jsonb, 87, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200088, 'Japanese — Uramaki Roll', 'asian', 'japanese', 'Philadelphia', 'ფილადელფია', 'nori, rice, salmon, cream cheese, tobiko, green onion, himalayan salt, teriyaki sauce', 'ნორი, ბრინჯი, ორაგული, კრემ ყველი, ტობიკო, მწვანე ხახვი, ჰიმალაის მარილი, ტერიაკის სოუსი', '42.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-uramaki-roll-philadelphia-8947015b.webp', '[]'::jsonb, 88, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200089, 'Japanese — Uramaki Roll', 'asian', 'japanese', 'Unagi', 'უნაგი', 'nori, rice, avocado, sesame, unagi, cream cheese, teriyaki', 'ნორი, ბრინჯი, ავოკადო, სეზამი, უნაგი, კრემ ყველი, ტერიაკი', '35.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-uramaki-roll-unagi-d83a44b9.webp', '[]'::jsonb, 89, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200090, 'Japanese — Uramaki Roll', 'asian', 'japanese', 'Tropical Shrimp', 'ტროპიკული კრევეტი', 'nori, rice, shrimp, salmon, avocado, tempura, mayo-mango', 'ნორი, ბრინჯი, კრევეტი, ორაგული, ავოკადო, ტემპურა, მაიო-მანგო', '33.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-uramaki-roll-tropical-shrimp-e011d09b.webp', '[]'::jsonb, 90, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200091, 'Japanese — Uramaki Roll', 'asian', 'japanese', 'Royal Philadelphia', 'სამეფო ფილადელფია', 'nori, rice, salmon, cream cheese, caviar, lemon zest', 'ნორი, ბრინჯი, ორაგული, კრემყველი, ხიზილალა, ლიმონის ცედრა', '48.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-uramaki-roll-royal-philadelphia-ccfa402f.webp', '[]'::jsonb, 91, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200092, 'Japanese — Uramaki Roll', 'asian', 'japanese', 'Spicy Philadelphia', 'ცხარე ფილადელფია', 'nori, rice, salmon, cream cheese, mayo-mango, chili pepper', 'ნორი, ბრინჯი, ორაგული, კრემყველი, მაიო-მანგო, ჩილი წიწაკა', '40.00 ₾', '', '[]'::jsonb, 92, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200093, 'Japanese — Futomaki', 'asian', 'japanese', 'Veggie Futomaki', 'ფუტომაკი ბოსტნეული', 'nori, rice, sesame, iceberg, cucumber, hiashi, tekuan', 'ნორი, ბრინჯი, სეზამი, აისბერგი, კიტრი, ჰიაში, ტეკუანი', '21.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-futomaki-veggie-futomaki-7e4d2105.webp', '[]'::jsonb, 93, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200094, 'Japanese — Futomaki', 'asian', 'japanese', 'Tuna Futomaki', 'ფუტომაკი თინუსი', 'nori, rice, ginger, tuna, spring onion, cream-cheese, cucumber', 'ნორი, ბრინჯი, ჯინჯერი, თინუსი, მწვანე ხახვი, კრემ-ყველი, კიტრი', '27.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-futomaki-tuna-futomaki-09b4635a.webp', '[]'::jsonb, 94, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200095, 'Japanese — Futomaki', 'asian', 'japanese', 'Salmon Futomaki', 'ფუტომაკი ორაგულით', 'nori, rice, salmon, cream-cheese, spring onion, crab', 'ნორი, ბრინჯი, ორაგული, კრემ-ყველი, მწვანე ხახვი, კიბორჩხალა', '32.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-futomaki-salmon-futomaki-d1ecf09b.webp', '[]'::jsonb, 95, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200096, 'Japanese — Poke Bowl', 'asian', 'japanese', 'Salmon Poke Bowl', 'ორაგულის თასი', 'Salmon, Sweet corn, Avocado, Carrot, Cucumber, Kimchi, Rice, Unagi sauce, Sesame seed, Spicy mayo', 'ორაგული, ტკბილი სიმინდი, ავოკადო, სტაფილო, კიტრი, კიმჩი, ბრინჯი, უნაგის სოუსი, სეზამის მარცვლები, ცხარე მაიონეზი', '28.00 ₾', '', '[]'::jsonb, 96, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200097, 'Japanese — Poke Bowl', 'asian', 'japanese', 'Tuna Poke Bowl', 'თინუსის თასი', 'Tuna, Cucumber, Carrot, Hiyashi wakame, Radish, Sesame seed, Rice, Unagi sauce, Wasabi Mayo', 'თინუსი, კიტრი, სტაფილო, ჰიაში ვაკამე, ბოლოკი, სეზამის მარცვლები, ბრინჯი, უნაგის სოუსი, ვასაბის მაიონეზი', '29.00 ₾', '', '[]'::jsonb, 97, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200098, 'Japanese — Poke Bowl', 'asian', 'japanese', 'Shrimp Poke Bowl', 'კრევეტის თასი', 'Shrimp, Edamame, Sweet corn, Carrot, Cucumber, Pickle ginger, Tobiko, Rice, Soya, Mayo', 'კრევეტი, ედამამე, ტკბილი სიმინდი, სტაფილო, კიტრი, მწნილი კოჭა, ტობიკო, ბრინჯი, სოიო, მაიონეზი', '25.00 ₾', '', '[]'::jsonb, 98, 'FM ASIAN 2026 MAY 31x46cm.pdf', 2),
  (200099, 'Drinks — White Classic', 'drinks', NULL, 'Faustino VII Blanco 2024, Bodegas Spain', 'ფაუსტინო VII 2024, Bodegas ესპანეთი', NULL, NULL, '52.00 ₾', '', '[]'::jsonb, 99, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200100, 'Drinks — White Classic', 'drinks', NULL, 'Lumina Pinot Grigio delle Venezie DOC 2024, Ruffino Italy', 'ლუმინა პინო გრიჯიო დელე ვენეციე, Ruffino იტალია', NULL, NULL, '61.00 ₾', '', '[]'::jsonb, 100, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200101, 'Drinks — White Classic', 'drinks', NULL, 'Riesling “vom Roten Schiefer” 2021, Germany', 'რიზლინგი „vom Roten Schiefer“ 2021 გერმანია', NULL, NULL, '82.00 ₾', '', '[]'::jsonb, 101, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200102, 'Drinks — White Classic', 'drinks', NULL, 'Hey French Bianco Veneto, Multivintage Pasqua Italy', 'ბიანკო ვენეტო, Multivintage Pasqua იტალია', NULL, NULL, '201.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-classic-hey-french-bianco-veneto-multivintage-pasqua-italy-fc171a6c.webp', '[]'::jsonb, 102, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200103, 'Drinks — White Classic', 'drinks', NULL, 'Graves Blanc, Reserve, Bordeaux 2022, Mouton Cadet France', 'გრეივს ბლანი, რეზერვი, ბორდო 2022, Mouton Cadet საფრანგეთი', NULL, NULL, '76.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-classic-graves-blanc-reserve-bordeaux-2022-mouton-cadet-france-97dd6ac2.webp', '[]'::jsonb, 103, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200104, 'Drinks — White Classic', 'drinks', NULL, 'Tsinandali, Naberauli', 'წინანდალი, ნაბერაული', NULL, NULL, '24.00 ₾', '', '[]'::jsonb, 104, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200105, 'Drinks — White Classic', 'drinks', NULL, 'Mtsvane, Kardanakhi 1888', 'მწვანე, კარდანახი 1888', NULL, NULL, '15.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-classic-mtsvane-kardanakhi-1888-65192427.webp', '[]'::jsonb, 105, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200106, 'Drinks — White Classic', 'drinks', NULL, 'Tsiskari, Eclipse, Tkatsiteli 2021', 'ცისკარი, ეკლიფსე, რქაწითელი 2021', NULL, NULL, '27.00 ₾', '', '[]'::jsonb, 106, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200107, 'Drinks — White Classic', 'drinks', NULL, 'Mtsvane, Shakriani Estate', 'მწვანე, შაქრიანი ესთეითი', NULL, NULL, '36.00 ₾', '', '[]'::jsonb, 107, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200108, 'Drinks — White Classic', 'drinks', NULL, 'Chinuri-Goruli Mtsvane, Gulodrava', 'ჩინური-გორული მწვანე, გულოდრავა', NULL, NULL, '42.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-classic-chinuri-goruli-mtsvane-gulodrava-573d989d.webp', '[]'::jsonb, 108, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200109, 'Drinks — White Classic', 'drinks', NULL, 'Atenuri, Gulodrava', 'ატენური, გულოდრავა', NULL, NULL, '42.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-classic-atenuri-gulodrava-d1edd923.webp', '[]'::jsonb, 109, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200110, 'Drinks — White Dry Qvevri', 'drinks', NULL, 'Tsolikauri, Anemo', 'ცოლიკაური, ანემო', NULL, NULL, '51.00 ₾', '', '[]'::jsonb, 110, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200111, 'Drinks — White Dry Qvevri', 'drinks', NULL, 'Goruli Mtsvane, Zedashe', 'გორული მწვანე, ზედაშე', NULL, NULL, '63.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-dry-qvevri-goruli-mtsvane-zedashe-d3cbfc96.webp', '[]'::jsonb, 111, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200112, 'Drinks — White Dry Qvevri', 'drinks', NULL, 'Mtsvane, Rtvelisi', 'მწვანე, რთველისი', NULL, NULL, '47.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-dry-qvevri-mtsvane-rtvelisi-6c23f455.webp', '[]'::jsonb, 112, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200113, 'Drinks — White Dry Qvevri', 'drinks', NULL, 'Rkatsiteli, Vardiashvili', 'რქაწითელი, ვარდიაშვილი', NULL, NULL, '31.00 ₾', '', '[]'::jsonb, 113, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200114, 'Drinks — White Dry Qvevri', 'drinks', NULL, 'Khikhvi, Pirveli Winery', 'ხიხვი, პირველი მეღვინეობა', NULL, NULL, '51.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-dry-qvevri-khikhvi-pirveli-winery-e9ed587e.webp', '[]'::jsonb, 114, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200115, 'Drinks — White Dry Qvevri', 'drinks', NULL, 'Kisi, Shakriani Estate', 'ქისი, შაქრიანი ესთეითი', NULL, NULL, '36.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-dry-qvevri-kisi-shakriani-estate-64352086.webp', '[]'::jsonb, 115, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200116, 'Drinks — White Semi Sweet', 'drinks', NULL, 'Tvishi, Naberauli', 'ტვიში, ნაბერაული', NULL, NULL, '81.00 ₾', '', '[]'::jsonb, 116, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200117, 'Drinks — White Semi Sweet', 'drinks', NULL, 'Gviani Mosavali, Barbale', 'გვიანი მოსავალი, ბარბალე', NULL, NULL, '56.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-semi-sweet-gviani-mosavali-barbale-bc3782e4.webp', '[]'::jsonb, 117, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200118, 'Drinks — Red Dry Classic', 'drinks', NULL, 'Faustino VII Tempranillo 2023, Bodegas Spain', 'ფაუსტინო VII ტემპრანილო 2023, Bodegas ესპანეთი', NULL, NULL, '52.00 ₾', '', '[]'::jsonb, 118, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200119, 'Drinks — Red Dry Classic', 'drinks', NULL, '10 Meses 2023, Portia Spain', '10 მესეს 2023, Portia ესპანეთი', NULL, NULL, '91.00 ₾', '', '[]'::jsonb, 119, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200120, 'Drinks — Red Dry Classic', 'drinks', NULL, '1877 Chianti DOCG, Ruffino Italy', '1877 ჩიანტი DOCG, Ruffino იტალია', NULL, NULL, '65.00 ₾', '', '[]'::jsonb, 120, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200121, 'Drinks — Red Dry Classic', 'drinks', NULL, 'Primitivo di Manduria DOC 2024, Tenute Orestiadi Italy', 'პრიმიტივო დი მანდურია DOC 2024, Tenute Orestiadi იტალია', NULL, NULL, '73.00 ₾', '', '[]'::jsonb, 121, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200122, 'Drinks — Red Dry Classic', 'drinks', NULL, 'Saint-Emilion, Reserve Bordeaux 2020, Mouton Cadet France', 'სან-ემილიონ, რეზერვ ბორდო 2020, Mouton Cadet საფრანგეთი', NULL, NULL, '102.00 ₾', '', '[]'::jsonb, 122, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200123, 'Drinks — Red Dry Classic', 'drinks', NULL, 'Lui’, Cabernet Sauvignon Veneto 2018, Pasqua Italy', 'ლუი, კაბერნე სოვინიონი ვენეტო 2018, Pasqua იტალია', NULL, NULL, '133.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-dry-classic-lui-cabernet-sauvignon-veneto-2018-pasqua-italy-73b50510.webp', '[]'::jsonb, 123, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200124, 'Drinks — Red Dry Classic', 'drinks', NULL, 'Rosso Veneto IGT 2021, Pasqua Italy', 'როსო ვენეტო IGT 2021, Pasqua იტალია', NULL, NULL, '77.00 ₾', '', '[]'::jsonb, 124, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200125, 'Drinks — Red Dry Classic', 'drinks', NULL, 'Saperavi Esabi, Eclipse', 'საფერავი ესაბი, ეკლიპსე', NULL, NULL, '45.00 ₾', '', '[]'::jsonb, 125, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200126, 'Drinks — Red Dry Classic', 'drinks', NULL, 'Saperavi Dzelshavi, Royal Khvanchkara', 'საფერავი ძელშავი, როიალ ხვანჭკარა', NULL, NULL, '40.00 ₾', '', '[]'::jsonb, 126, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200127, 'Drinks — Red Dry Classic', 'drinks', NULL, 'Asuretuli, Marbano', 'ასურეთული, მარბანო', NULL, NULL, '54.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-dry-classic-asuretuli-marbano-e9014015.webp', '[]'::jsonb, 127, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200128, 'Drinks — Red Dry Classic', 'drinks', NULL, 'Saperavi, Shakriani Estate', 'საფერავი, შაქრიანი ესთეითი', NULL, NULL, '36.00 ₾', '', '[]'::jsonb, 128, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200129, 'Drinks — Red Dry Classic', 'drinks', NULL, 'Otskhanuri Sapere, Gulodrava', 'ოცხანური საფერე, გულოდრავა', NULL, NULL, '42.00 ₾', '', '[]'::jsonb, 129, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200130, 'Drinks — Red Dry Classic', 'drinks', NULL, 'Saperavi, Gulodrava', 'საფერავი, გულოდრავა', NULL, NULL, '42.00 ₾', '', '[]'::jsonb, 130, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200131, 'Drinks — Red Dry Classic', 'drinks', NULL, 'Saperavi, Rtvelisi', 'საფერავი, რთველისი', NULL, NULL, '45.00 ₾', '', '[]'::jsonb, 131, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200132, 'Drinks — Red Dry Qvevri', 'drinks', NULL, 'Saperavi, Anemo', 'საფერავი, ანემო', NULL, NULL, '45.00 ₾', '', '[]'::jsonb, 132, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200133, 'Drinks — Red Dry Qvevri', 'drinks', NULL, 'Shavkapito, Zedashe', 'შავკაპიტო, ზედაშე', NULL, NULL, '54.00 ₾', '', '[]'::jsonb, 133, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200134, 'Drinks — Red Dry Qvevri', 'drinks', NULL, 'Asuretuli, Zedashe', 'ასურეთული, ზედაშე', NULL, NULL, '54.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-dry-qvevri-asuretuli-zedashe-36fda36e.webp', '[]'::jsonb, 134, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200135, 'Drinks — Red Dry Qvevri', 'drinks', NULL, 'Saperavi, Shakriani Estate', 'საფერავი, შაქრიანი ესთეითი', NULL, NULL, '41.00 ₾', '', '[]'::jsonb, 135, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200136, 'Drinks — Red Semi Sweet', 'drinks', NULL, 'Kindzmarauli, Rtvelisi', 'ქინძმარაული რთველისი', NULL, NULL, '32.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-semi-sweet-kindzmarauli-rtvelisi-61ef3100.webp', '[]'::jsonb, 136, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200137, 'Drinks — Red Semi Sweet', 'drinks', NULL, 'Khvanchkara, Royal Khvanchkara', 'ხვანჭკარა, როიალ ხვანჭკარა', NULL, NULL, '72.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-semi-sweet-khvanchkara-royal-khvanchkara-d46dd3ce.webp', '[]'::jsonb, 137, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200138, 'Drinks — Red Semi Sweet', 'drinks', NULL, 'Usakhelauri, Royal Racha', 'უსახელაური, როიალ რაჭა', NULL, NULL, '207.00 ₾', '', '[]'::jsonb, 138, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200139, 'Drinks — Rose', 'drinks', NULL, '11 Minutes, Rose Trevenezie 2023, Pasqua Italy', '11 მინუტეს, როზე ტრევენეციე 2023, Pasqua იტალია', NULL, NULL, '88.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-rose-11-minutes-rose-trevenezie-2023-pasqua-italy-14102dd4.webp', '[]'::jsonb, 139, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200140, 'Drinks — Rose', 'drinks', NULL, 'Saperavi Rose, Chelti', 'საფერავი როზე, ჩელთი', NULL, NULL, '27.00 ₾', '', '[]'::jsonb, 140, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200141, 'Drinks — Rose', 'drinks', NULL, 'Shavkapito Rose, Amosa', 'შავკაპიტო როზე, ამოსა', NULL, NULL, '34.00 ₾', '', '[]'::jsonb, 141, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200142, 'Drinks — Rose', 'drinks', NULL, 'Usakhelauri Rose, Naberauli', 'უსახელაური როზე, ნაბერაული', NULL, NULL, '63.00 ₾', '', '[]'::jsonb, 142, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200143, 'Drinks — Sparkling Wine', 'drinks', NULL, 'Askaneli Brut', 'ასკანელი ბრუტი', NULL, NULL, '42.00 ₾', '', '[]'::jsonb, 143, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200144, 'Drinks — Sparkling Wine', 'drinks', NULL, 'Bodegas Faustino Cava Brut', 'ბოდეგას ფაუსტინო', NULL, NULL, '61.00 ₾', '', '[]'::jsonb, 144, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200145, 'Drinks — Sparkling Wine', 'drinks', NULL, 'Soffio Prosecco DOC Millesimato 2025', 'პროსეკო', NULL, NULL, '83.00 ₾', '', '[]'::jsonb, 145, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200146, 'Drinks — Wine by the Glass', 'drinks', NULL, 'Faustino Cava Brut, Bodegas', 'ფაუსტინო, Bodegas', 'Sparkling Wine, Spain', 'ცქრიალა ღვინო, ესპანეთი', '17.00 ₾', '', '[]'::jsonb, 146, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200147, 'Drinks — Wine by the Glass', 'drinks', NULL, 'Pinot Grigio, Ruffino', 'პინო გრიჯიო, Ruffino', 'White Classic, Italy', 'თეთრი კლასიკური, იტალია', '18.00 ₾', '', '[]'::jsonb, 147, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200148, 'Drinks — Wine by the Glass', 'drinks', NULL, 'Primitivo di Manduria', 'პრიმიტივო დი მანდურია', 'Red Dry, Italy', 'წითელი მშრალი, იტალია', '24.00 ₾', '', '[]'::jsonb, 148, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200149, 'Drinks — Wine by the Glass', 'drinks', NULL, 'Cava Brut, Campo Viejo', 'კავა ბრუტი, Campo Viejo', 'Sparkling Wine, Spain', 'ცქრიალა ღვინო, ესპანეთი', '20.00 ₾', '', '[]'::jsonb, 149, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200150, 'Drinks — Wine by the Glass', 'drinks', NULL, 'Monastrell 2021, Bodegas Carchelo', 'მონასტრელ 2021, Bodegas Carchelo', 'Red Dry, Spain', 'წითელი მშრალი, ესპანეთი', '18.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-wine-by-the-glass-monastrell-2021-bodegas-carchelo-0a81c591.webp', '[]'::jsonb, 150, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200151, 'Drinks — Wine by the Glass', 'drinks', NULL, 'EYA Verdejo 2023, Bodegas Carchelo', 'ეა ვერდეხო 2023, Bodegas Carchelo', 'White Dry, Spain', 'თეთრი მშრალი, ესპანეთი', '16.00 ₾', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-wine-by-the-glass-eya-verdejo-2023-bodegas-carchelo-01265ed9.webp', '[]'::jsonb, 151, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200152, 'Drinks — Wine by the Glass', 'drinks', NULL, 'Tsolikauri Kisi, Rtvelisi', 'ცოლიკაური ქისი, რთველისი', NULL, NULL, '18.00 ₾', '', '[]'::jsonb, 152, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200153, 'Drinks — Wine by the Glass', 'drinks', NULL, 'Tsinandali, Chelti', 'წინანდალი, ჩელთი', NULL, NULL, '14.00 ₾', '', '[]'::jsonb, 153, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200154, 'Drinks — Wine by the Glass', 'drinks', NULL, 'Tvishi, Rtvelisi', 'ტვიში, რთველისი', NULL, NULL, '18.00 ₾', '', '[]'::jsonb, 154, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200155, 'Drinks — Wine by the Glass', 'drinks', NULL, 'Saperavi, Rtvelisi', 'საფერავი, რთველისი', NULL, NULL, '15.00 ₾', '', '[]'::jsonb, 155, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 1),
  (200156, 'Drinks — Refreshing Beverages', 'drinks', NULL, 'Borjomi Sparkling Water', 'ბორჯომი', NULL, NULL, '5.00 ₾', '', '[]'::jsonb, 156, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200157, 'Drinks — Refreshing Beverages', 'drinks', NULL, 'Bakuriani Mineral Water', 'ბაკურიანი', NULL, NULL, '4.00 ₾', '', '[]'::jsonb, 157, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200158, 'Drinks — Refreshing Beverages', 'drinks', NULL, 'Limonati by Borjomi', 'ლიმონათი ბორჯომი', 'Pear / Citrus / Tangerine / Tarragon', 'მსხალი / ციტრუსი / მანდარინი / ტარხუნა', '6.00 ₾', '', '[]'::jsonb, 158, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200159, 'Drinks — Refreshing Beverages', 'drinks', NULL, 'Coca-Cola', 'კოკა კოლა', NULL, NULL, '5.00 ₾', '', '[]'::jsonb, 159, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200160, 'Drinks — Refreshing Beverages', 'drinks', NULL, 'Coca-Cola Zero', 'კოკა კოლა ზერო', NULL, NULL, '5.00 ₾', '', '[]'::jsonb, 160, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200161, 'Drinks — Refreshing Beverages', 'drinks', NULL, 'Kombucha', 'კომბუჩა', NULL, NULL, '11.00 ₾', '', '[]'::jsonb, 161, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200162, 'Drinks — Refreshing Beverages', 'drinks', NULL, 'Juice', 'წვენი', NULL, NULL, '7.00 ₾', '', '[]'::jsonb, 162, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200163, 'Drinks — Refreshing Beverages', 'drinks', NULL, 'Fresh', 'ფრეში', 'Orange, grapefruit', 'ფორთოხალი, გრეიფრუტი', '17.00 ₾', '', '[]'::jsonb, 163, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200164, 'Drinks — Refreshing Beverages', 'drinks', NULL, 'Homemade Lemonade with Mint and Lemon', 'ლიმნის და პიტნის ლიმონათი', NULL, NULL, '15.00 ₾', '', '[]'::jsonb, 164, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200165, 'Drinks — Refreshing Beverages', 'drinks', NULL, 'Homemade Lemonade Citrus', 'ლიმონათი ციტრუსის', NULL, NULL, '15.00 ₾', '', '[]'::jsonb, 165, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200166, 'Drinks — Refreshing Beverages', 'drinks', NULL, 'Homemade Lemonade Berries', 'ლიმონათი კენკრის', NULL, NULL, '15.00 ₾', '', '[]'::jsonb, 166, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200167, 'Drinks — Refreshing Beverages', 'drinks', NULL, 'Laghidze Waters', 'ლაღიძის წყლები', NULL, NULL, '8.00 ₾', '', '[]'::jsonb, 167, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200168, 'Drinks — Coffee & Tea', 'drinks', NULL, 'Espresso', 'ესპრესო', NULL, NULL, '8.00 ₾', '', '[]'::jsonb, 168, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200169, 'Drinks — Coffee & Tea', 'drinks', NULL, 'Americano', 'ამერიკანო', NULL, NULL, '8.00 ₾', '', '[]'::jsonb, 169, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200170, 'Drinks — Coffee & Tea', 'drinks', NULL, 'Turkish Coffee', 'თურქული ყავა', NULL, NULL, '6.00 ₾', '', '[]'::jsonb, 170, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200171, 'Drinks — Coffee & Tea', 'drinks', NULL, 'Cappuccino', 'კაპუჩინო', NULL, NULL, '10.00 ₾', '', '[]'::jsonb, 171, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200172, 'Drinks — Coffee & Tea', 'drinks', NULL, 'Black Tea', 'შავი ჩაი', NULL, NULL, '12.00 ₾', '', '[]'::jsonb, 172, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200173, 'Drinks — Coffee & Tea', 'drinks', NULL, 'Green Tea', 'მწვანე ჩაი', NULL, NULL, '12.00 ₾', '', '[]'::jsonb, 173, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200174, 'Drinks — Coffee & Tea', 'drinks', NULL, 'Fruit Tea', 'ხილის ჩაი', NULL, NULL, '12.00 ₾', '', '[]'::jsonb, 174, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200175, 'Drinks — Coffee & Tea', 'drinks', NULL, 'Double Espresso', 'ორმაგი ესპრესო', NULL, NULL, '12.00 ₾', '', '[]'::jsonb, 175, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200176, 'Drinks — Coffee & Tea', 'drinks', NULL, 'Latte', 'ლატე', NULL, NULL, '12.00 ₾', '', '[]'::jsonb, 176, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200177, 'Drinks — Coffee & Tea', 'drinks', NULL, 'Mint & Bekondara Tea', 'პიტნის და ბექონდარას ჩაი', NULL, NULL, '15.00 ₾', '', '[]'::jsonb, 177, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200178, 'Drinks — Coffee & Tea', 'drinks', NULL, 'Ice Coffee', 'ცივი ყავა', NULL, NULL, '13.00 ₾', '', '[]'::jsonb, 178, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200179, 'Drinks — Coffee & Tea', 'drinks', NULL, 'Ice Coffee with Ice Cream', 'ცივი ყავა ნაყინით', NULL, NULL, '16.00 ₾', '', '[]'::jsonb, 179, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200180, 'Drinks — Beer', 'drinks', NULL, 'Super Bock', 'სუპერ ბოკი', NULL, NULL, '14.00 ₾', '', '[]'::jsonb, 180, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200181, 'Drinks — Beer', 'drinks', NULL, 'Qarva', 'ქარვა', NULL, NULL, '11.00 ₾', '', '[]'::jsonb, 181, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200182, 'Drinks — Beer', 'drinks', NULL, 'Corona', 'კორონა', NULL, NULL, '16.00 ₾', '', '[]'::jsonb, 182, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200183, 'Drinks — Beer', 'drinks', NULL, 'Stella', 'სტელა', NULL, NULL, '14.00 ₾', '', '[]'::jsonb, 183, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200184, 'Drinks — Beer', 'drinks', NULL, 'Lowenbrau', 'ლოვენბრაუ', NULL, NULL, '12.00 ₾', '', '[]'::jsonb, 184, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200185, 'Drinks — Beer', 'drinks', NULL, 'Leffe', 'ლეფე', NULL, NULL, '15.00 ₾', '', '[]'::jsonb, 185, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200186, 'Drinks — Vodka', 'drinks', NULL, 'Absolut', 'აბსოლუტი', NULL, NULL, '10.00 ₾', '', '[]'::jsonb, 186, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200187, 'Drinks — Vodka', 'drinks', NULL, 'Grey Goose', 'გრეი გუსი', NULL, NULL, '22.00 ₾', '', '[]'::jsonb, 187, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200188, 'Drinks — Vodka', 'drinks', NULL, 'Stolichnaya', 'სტოლიჩნაია', NULL, NULL, '12.00 ₾', '', '[]'::jsonb, 188, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200189, 'Drinks — Chacha', 'drinks', NULL, 'Chef Chacha', 'შეფის ჭაჭა', NULL, NULL, '10.00 ₾', '', '[]'::jsonb, 189, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200190, 'Drinks — Gin', 'drinks', NULL, 'Tanqueray London Dry', 'თენქერეი London Dry', NULL, NULL, '14.00 ₾', '', '[]'::jsonb, 190, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200191, 'Drinks — Gin', 'drinks', NULL, 'Tanqueray 10', 'თენქერეი 10', NULL, NULL, '20.00 ₾', '', '[]'::jsonb, 191, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200192, 'Drinks — Gin', 'drinks', NULL, 'Hendrick’s', 'ჰენდრიკსი', NULL, NULL, '20.00 ₾', '', '[]'::jsonb, 192, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200193, 'Drinks — Tequila', 'drinks', NULL, 'Don Julio Blanco', 'დონ ხულიო Blanco', NULL, NULL, '45.00 ₾', '', '[]'::jsonb, 193, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200194, 'Drinks — Tequila', 'drinks', NULL, 'Don Julio Reposado', 'დონ ხულიო Reposado', NULL, NULL, '51.00 ₾', '', '[]'::jsonb, 194, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200195, 'Drinks — Vermouth and Bitters', 'drinks', NULL, 'Martini', 'მარტინი', 'Bianco, Rosso, Extra Dry', NULL, '14.00 ₾', '', '[]'::jsonb, 195, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200196, 'Drinks — Vermouth and Bitters', 'drinks', NULL, 'Aperol', 'აპეროლი', NULL, NULL, '14.00 ₾', '', '[]'::jsonb, 196, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200197, 'Drinks — Vermouth and Bitters', 'drinks', NULL, 'Jägermeister', 'იაგერმაისტერი', NULL, NULL, '14.00 ₾', '', '[]'::jsonb, 197, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200198, 'Drinks — Rum & Liquor', 'drinks', NULL, 'Captain Morgan', 'კაპიტან მორგანი', NULL, NULL, '12.00 ₾', '', '[]'::jsonb, 198, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200199, 'Drinks — Rum & Liquor', 'drinks', NULL, 'Zacapa 23y', 'ზაკაპა 23წ', NULL, NULL, '48.00 ₾', '', '[]'::jsonb, 199, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200200, 'Drinks — Rum & Liquor', 'drinks', NULL, 'Baileys', 'ბეილისი', NULL, NULL, '12.00 ₾', '', '[]'::jsonb, 200, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200201, 'Drinks — Whiskey', 'drinks', NULL, 'Johnnie Walker Red Label', 'ჯონი უოკერი Red Label', NULL, NULL, '12.00 ₾', '', '[]'::jsonb, 201, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200202, 'Drinks — Whiskey', 'drinks', NULL, 'Johnnie Walker Black Label', 'ჯონი უოკერი Black Label', NULL, NULL, '18.00 ₾', '', '[]'::jsonb, 202, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200203, 'Drinks — Whiskey', 'drinks', NULL, 'Singleton 12y', 'სინგლტონი 12წ', NULL, NULL, '20.00 ₾', '', '[]'::jsonb, 203, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200204, 'Drinks — Whiskey', 'drinks', NULL, 'Singleton 15y', 'სინგლტონი 15წ', NULL, NULL, '32.00 ₾', '', '[]'::jsonb, 204, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200205, 'Drinks — Whiskey', 'drinks', NULL, 'Talisker 10y', 'ტალისკერი 10წ', NULL, NULL, '35.00 ₾', '', '[]'::jsonb, 205, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200206, 'Drinks — Whiskey', 'drinks', NULL, 'Bulleit Rye', 'ბულეთ რეი', NULL, NULL, '22.00 ₾', '', '[]'::jsonb, 206, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200207, 'Drinks — Whiskey', 'drinks', NULL, 'Tullamore', 'ტულამორი', NULL, NULL, '15.00 ₾', '', '[]'::jsonb, 207, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200208, 'Drinks — Whiskey', 'drinks', NULL, 'Kilbeggan', 'კილბეგანი', NULL, NULL, '15.00 ₾', '', '[]'::jsonb, 208, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200209, 'Drinks — Brandy and Cognac', 'drinks', NULL, 'Askaneli 3y', 'ასკანელი 3წ', NULL, NULL, '12.00 ₾', '', '[]'::jsonb, 209, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200210, 'Drinks — Brandy and Cognac', 'drinks', NULL, 'Askaneli 6y', 'ასკანელი 6წ', NULL, NULL, '16.00 ₾', '', '[]'::jsonb, 210, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200211, 'Drinks — Brandy and Cognac', 'drinks', NULL, 'Askaneli VSOP', 'ასკანელი VSOP', NULL, NULL, '42.00 ₾', '', '[]'::jsonb, 211, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200212, 'Drinks — Brandy and Cognac', 'drinks', NULL, 'Rémy Martin VSOP', 'რემი მარტინი VSOP', NULL, NULL, '36.00 ₾', '', '[]'::jsonb, 212, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200213, 'Drinks — Cocktail', 'drinks', NULL, 'Figleton', NULL, 'Singleton | Fig Jam | Angostura Bitters', NULL, '30.00 ₾', '', '[]'::jsonb, 213, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200214, 'Drinks — Cocktail', 'drinks', NULL, 'Orchard Boulevardier', NULL, 'Singleton | Apple & Pear vermouth | Campari', NULL, '30.00 ₾', '', '[]'::jsonb, 214, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200215, 'Drinks — Cocktail', 'drinks', NULL, 'Espresso Martini', NULL, 'Espresso | Vodka Absolut | Kahlua', NULL, '30.00 ₾', '', '[]'::jsonb, 215, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200216, 'Drinks — Cocktail', 'drinks', NULL, 'Lovely Weekend', NULL, 'Vodka Absolut | Campari | Maracuja puree | Grapefruit Juice | Lemon Fresh', NULL, '30.00 ₾', '', '[]'::jsonb, 216, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200217, 'Drinks — Cocktail', 'drinks', NULL, 'Miss Sunshine', NULL, 'Tequila | Maracuja puree | Amaretto | Lemon Fresh', NULL, '30.00 ₾', '', '[]'::jsonb, 217, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200218, 'Drinks — Cocktail', 'drinks', NULL, 'Moscow Mule', NULL, 'Vodka Absolut | Lemon Fresh | Ginger Sirup', NULL, '30.00 ₾', '', '[]'::jsonb, 218, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200219, 'Drinks — Cocktail', 'drinks', NULL, 'Rum Berries', NULL, 'Captain Morgan white | Cointreau | Berrie Puree | Pomegranate Juice | Lemon Fresh | Berries', NULL, '30.00 ₾', '', '[]'::jsonb, 219, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200220, 'Drinks — Cocktail', 'drinks', NULL, 'Cucumber and Basil Smash', NULL, 'Tanquerey | Cucumber sirup | Basil Sirup | Lemon Fresh', NULL, '30.00 ₾', '', '[]'::jsonb, 220, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200221, 'Drinks — Cocktail', 'drinks', NULL, 'Negroni', NULL, 'Tanquerey | Martini Rosso | Campari', NULL, '30.00 ₾', '', '[]'::jsonb, 221, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200222, 'Drinks — Cocktail', 'drinks', NULL, 'Aperol Spritz', NULL, 'Aperol | Sparkling Wine', NULL, '30.00 ₾', '', '[]'::jsonb, 222, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200223, 'Drinks — Cocktail', 'drinks', NULL, 'Gin Tonic', NULL, 'Tanquerey | Tonic', NULL, '30.00 ₾', '', '[]'::jsonb, 223, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200224, 'Drinks — Cocktail', 'drinks', NULL, 'Mohito', NULL, 'Captain Morgan white | Schweppes', NULL, '30.00 ₾', '', '[]'::jsonb, 224, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200225, 'Drinks — Cocktail', 'drinks', NULL, 'Cuba Libre', NULL, 'Captain Morgan white | Coca-Cola | Lime Fresh', NULL, '30.00 ₾', '', '[]'::jsonb, 225, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200226, 'Drinks — Cocktail', 'drinks', NULL, 'Long Island', NULL, 'Vodka Absolut | Captain Morgan white | Tequilla | Tanquerey | Cointreau', NULL, '30.00 ₾', '', '[]'::jsonb, 226, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200227, 'Drinks — Cocktail', 'drinks', NULL, 'Elder Johnny', NULL, 'Johnnie Walker Black Label | Elderflower | Orange Bitter’s', NULL, '30.00 ₾', '', '[]'::jsonb, 227, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2),
  (200228, 'Drinks — Cocktail', 'drinks', NULL, 'Smashing Walk', NULL, 'Johnnie Walker Black Label | Honey & Ginger Syrup | Lemon | Angostura Bitter', NULL, '30.00 ₾', '', '[]'::jsonb, 228, 'FM  DRINKS 2026 MAY 31x44cm.pdf', 2);

-- Dummy rows are replaceable; the three asserted model rows remain in place.
DELETE FROM public.menu_items WHERE restaurant_id = 73 AND id NOT IN (1383, 1385, 1421);

UPDATE public.menu_items m SET
  category_id = c.id, name_en = src.name_en, name_ka = src.name_ka, name_ru = NULL,
  description_en = src.description_en, description_ka = src.description_ka, description_ru = NULL,
  price = src.price, price_old = NULL, variants = src.variants, addons = '[]'::jsonb,
  sort_order = src.sort_order, visible = true, featured = false
FROM _fm_items src JOIN public.categories c ON c.restaurant_id = 73 AND c.name_en = src.category_en
WHERE m.restaurant_id = 73 AND m.id = src.preserved_id AND src.preserved_id IN (1383, 1385, 1421);

INSERT INTO public.menu_items (restaurant_id, category_id, name_en, name_ka, name_ru, description_en, description_ka, description_ru, price, price_old, model, model_usdz, thumbnail_url, is_3d, ar_scale, thumb_3d, text_only, featured, addons, variants, sort_order, visible)
SELECT 73, c.id, src.name_en, src.name_ka, NULL, src.description_en, src.description_ka, NULL, src.price, NULL, '', '', src.thumbnail_url, false, 1, false, src.thumbnail_url = '', false, '[]'::jsonb, src.variants, src.sort_order, true
FROM _fm_items src JOIN public.categories c ON c.restaurant_id = 73 AND c.name_en = src.category_en
WHERE src.preserved_id NOT IN (1383, 1385, 1421);

-- Only categories owned by this restaurant and absent from the official manifest are retired.
DELETE FROM public.categories c WHERE c.restaurant_id = 73 AND NOT EXISTS (SELECT 1 FROM _fm_categories wanted WHERE wanted.name_en = c.name_en);

DO $$
BEGIN
  IF (SELECT count(*) FROM public.menu_items WHERE restaurant_id = 73 AND visible) <> 228 THEN RAISE EXCEPTION 'expected 228 visible items'; END IF;
  IF (SELECT count(*) FROM public.categories WHERE restaurant_id = 73) <> 44 THEN RAISE EXCEPTION 'expected 44 categories'; END IF;
  IF (SELECT count(*) FROM public.menu_items WHERE restaurant_id = 73 AND is_3d) <> 3 THEN RAISE EXCEPTION 'expected exactly 3 3D items'; END IF;
  IF EXISTS (SELECT 1 FROM _fm_preserved p LEFT JOIN public.menu_items m ON m.id = p.id AND m.restaurant_id = 73 WHERE m.id IS NULL OR m.model IS DISTINCT FROM p.model OR m.model_usdz IS DISTINCT FROM p.model_usdz OR m.thumbnail_url IS DISTINCT FROM p.thumbnail_url OR m.ar_scale IS DISTINCT FROM p.ar_scale OR m.is_3d IS DISTINCT FROM p.is_3d OR m.thumb_3d IS DISTINCT FROM p.thumb_3d) THEN RAISE EXCEPTION 'preserved 3D media changed'; END IF;
  IF (SELECT count(*) FROM public.menu_items WHERE restaurant_id = 73 AND thumbnail_url LIKE 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/%') <> 42 THEN RAISE EXCEPTION 'expected 42 mapped catalogue images'; END IF;
  IF EXISTS (SELECT 1 FROM public.menu_items WHERE restaurant_id = 73 AND id NOT IN (1383,1385,1421) AND (is_3d OR thumb_3d OR COALESCE(model,'') <> '' OR COALESCE(model_usdz,'') <> '' OR text_only IS DISTINCT FROM (COALESCE(thumbnail_url,'') = ''))) THEN RAISE EXCEPTION 'non-preserved media flags invalid'; END IF;
    IF EXISTS (SELECT 1 FROM public.menu_items m JOIN public.categories c ON c.id = m.category_id WHERE m.restaurant_id = 73 GROUP BY c.name_en, m.name_en HAVING count(*) > 1) THEN RAISE EXCEPTION 'duplicate logical item'; END IF;
  IF EXISTS (SELECT 1 FROM public.menu_items WHERE restaurant_id = 73 AND (name_ru IS NOT NULL OR description_ru IS NOT NULL)) THEN RAISE EXCEPTION 'unexpected Russian catalogue copy'; END IF;
  IF EXISTS (SELECT 1 FROM public.menu_items m LEFT JOIN public.categories c ON c.id = m.category_id AND c.restaurant_id = m.restaurant_id WHERE m.restaurant_id = 73 AND c.id IS NULL) THEN RAISE EXCEPTION 'orphan/cross-tenant category'; END IF;
  IF EXISTS (SELECT 1 FROM public.categories WHERE restaurant_id <> 73 AND name_en LIKE ANY (ARRAY['Georgian — %','Thai — %','Japanese — %','Drinks — %'])) THEN NULL; END IF; -- read-only: never mutate another tenant
  IF EXISTS (SELECT 1 FROM public.menu_items WHERE restaurant_id = 73 AND (COALESCE(name_en,'') LIKE '%Ã%' OR COALESCE(name_ka,'') LIKE '%Ã%' OR COALESCE(description_ka,'') LIKE '%Ã%')) THEN RAISE EXCEPTION 'possible mojibake'; END IF;
END $$;

SELECT count(*) AS items, count(*) FILTER (WHERE is_3d) AS models, count(*) FILTER (WHERE thumbnail_url LIKE 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/%') AS mapped_images FROM public.menu_items WHERE restaurant_id = 73;
ROLLBACK;
