-- Name: 2026-06-28_burger_lions_live_schema
-- Purpose: Make the static Burger Lions site and Next.js admin panel use the same Supabase data shape.
-- Run in Supabase SQL Editor for project lwdpegloznhpcecivhfy. Safe to re-run.

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  name_en text not null,
  name_ka text not null,
  sort_order integer not null default 0,
  created_at timestamptz not null default now(),
  unique (name_en)
);

create table if not exists public.menu_items (
  id bigint generated by default as identity primary key,
  name_en text not null,
  name_ka text not null default '',
  description_en text not null default '',
  description_ka text not null default '',
  price text not null default '',
  category_id bigint references public.categories(id) on delete set null,
  model text not null default '',
  model_usdz text not null default '',
  sort_order integer not null default 0,
  visible boolean not null default true,
  ar_scale numeric not null default 1.0,
  thumbnail_url text not null default '',
  thumb_3d boolean not null default false,
  created_at timestamptz not null default now(),
  unique (name_en)
);

create table if not exists public.theme_config (
  key text primary key,
  value text not null default '',
  updated_at timestamptz not null default now()
);

create table if not exists public.events (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  session_id text not null,
  visitor_id text not null,
  event text not null
);

alter table public.events add column if not exists item_index integer;
alter table public.events add column if not exists item_name text;
alter table public.events add column if not exists category text;
alter table public.events add column if not exists lang text;
alter table public.events add column if not exists ar_cap text;
alter table public.events add column if not exists platform text;
alter table public.events add column if not exists extra jsonb;
alter table public.menu_items add column if not exists model_usdz text not null default '';
alter table public.menu_items add column if not exists visible boolean not null default true;
alter table public.menu_items add column if not exists ar_scale numeric not null default 1.0;
alter table public.menu_items add column if not exists thumbnail_url text not null default '';
alter table public.menu_items add column if not exists thumb_3d boolean not null default false;

alter table public.categories enable row level security;
alter table public.menu_items enable row level security;
alter table public.theme_config enable row level security;
alter table public.events enable row level security;

drop policy if exists categories_public_read on public.categories;
create policy categories_public_read on public.categories for select using (true);
drop policy if exists menu_items_public_read_visible on public.menu_items;
create policy menu_items_public_read_visible on public.menu_items for select using (true);
drop policy if exists theme_config_public_read on public.theme_config;
create policy theme_config_public_read on public.theme_config for select using (true);
drop policy if exists events_public_insert on public.events;
create policy events_public_insert on public.events for insert with check (true);
drop policy if exists events_auth_read on public.events;
create policy events_auth_read on public.events for select using (auth.role() = 'authenticated');
drop policy if exists categories_auth_write on public.categories;
create policy categories_auth_write on public.categories for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists menu_items_auth_write on public.menu_items;
create policy menu_items_auth_write on public.menu_items for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');
drop policy if exists theme_config_auth_write on public.theme_config;
create policy theme_config_auth_write on public.theme_config for all using (auth.role() = 'authenticated') with check (auth.role() = 'authenticated');

grant usage on schema public to anon, authenticated;
grant select on public.categories, public.menu_items, public.theme_config to anon, authenticated;
grant insert on public.events to anon, authenticated;
grant select on public.events to authenticated;
grant select, insert, update, delete on public.categories, public.menu_items, public.theme_config to authenticated;
grant usage, select on all sequences in schema public to anon, authenticated;

-- Required for idempotent seed upserts, including projects where the tables already existed.
create unique index if not exists categories_name_en_key on public.categories (name_en);
create unique index if not exists menu_items_name_en_key on public.menu_items (name_en);

-- Seed fallback Burger Lions menu into the live DB if it is empty/missing rows.
insert into public.categories (name_en, name_ka, sort_order) values ('Burgers', 'ბურგერები', 1) on conflict (name_en) do update set name_ka = excluded.name_ka, sort_order = excluded.sort_order;
insert into public.categories (name_en, name_ka, sort_order) values ('Sides', 'გარნირი | სოუსები', 2) on conflict (name_en) do update set name_ka = excluded.name_ka, sort_order = excluded.sort_order;
insert into public.categories (name_en, name_ka, sort_order) values ('Desserts', 'დესერტები', 3) on conflict (name_en) do update set name_ka = excluded.name_ka, sort_order = excluded.sort_order;

insert into public.menu_items (name_en, name_ka, description_en, description_ka, price, category_id, model, model_usdz, sort_order, visible, ar_scale, thumbnail_url, thumb_3d) values (
  'BigBurger', 'ბიგბურგერი', '600g beef, 5 layers cheddar cheese, 4 layers bacon, special sauce, pickles, iceberg lettuce, burger bun.', 'ხორცი 600 გრ, ყველი ჩედარი 5 ფენა, ბეკონი 4 ფენა, სპეც სოუსი, მჟავე კიტრი, აისბერგი, ბურგერის ფუნთუშა.', '14 ₾', (select id from public.categories where name_en = 'Burgers'), 'https://pub-3c68559de18f4aee94d127e180937bdd.r2.dev/druidi_balanced_30k_2k.glb', 'https://pub-3c68559de18f4aee94d127e180937bdd.r2.dev/druidi_balanced_30k_2k.usdz', 1, true, 1.5181, 'https://pub-3c68559de18f4aee94d127e180937bdd.r2.dev/burger_poster.webp', true
) on conflict (name_en) do update set
  name_ka = excluded.name_ka, description_en = excluded.description_en, description_ka = excluded.description_ka,
  price = excluded.price, category_id = excluded.category_id, model = excluded.model, model_usdz = excluded.model_usdz,
  sort_order = excluded.sort_order, visible = excluded.visible, ar_scale = excluded.ar_scale,
  thumbnail_url = excluded.thumbnail_url, thumb_3d = excluded.thumb_3d;
insert into public.menu_items (name_en, name_ka, description_en, description_ka, price, category_id, model, model_usdz, sort_order, visible, ar_scale, thumbnail_url, thumb_3d) values (
  'Hot Dog', 'ჰოთ დოგი', 'classic hot dog', 'კლასიკური ჰოთ დოგი', '4 ₾', (select id from public.categories where name_en = 'Sides'), 'https://pub-3c68559de18f4aee94d127e180937bdd.r2.dev/hot_dog_draco.glb', 'https://pub-3c68559de18f4aee94d127e180937bdd.r2.dev/hot_dog.usdz', 2, true, 0.9312, 'https://pub-3c68559de18f4aee94d127e180937bdd.r2.dev/hot_dog_poster.webp', true
) on conflict (name_en) do update set
  name_ka = excluded.name_ka, description_en = excluded.description_en, description_ka = excluded.description_ka,
  price = excluded.price, category_id = excluded.category_id, model = excluded.model, model_usdz = excluded.model_usdz,
  sort_order = excluded.sort_order, visible = excluded.visible, ar_scale = excluded.ar_scale,
  thumbnail_url = excluded.thumbnail_url, thumb_3d = excluded.thumb_3d;
insert into public.menu_items (name_en, name_ka, description_en, description_ka, price, category_id, model, model_usdz, sort_order, visible, ar_scale, thumbnail_url, thumb_3d) values (
  'Croissant', 'კრუასანი', 'Classic croissant with chocolate', 'კლასიკური კროასანი შოკოლადით', '2.5 ₾', (select id from public.categories where name_en = 'Desserts'), 'https://pub-3c68559de18f4aee94d127e180937bdd.r2.dev/croissant_draco.glb', 'https://pub-3c68559de18f4aee94d127e180937bdd.r2.dev/croissant.usdz', 3, true, 0.9, 'https://pub-3c68559de18f4aee94d127e180937bdd.r2.dev/croissant_poster.webp', true
) on conflict (name_en) do update set
  name_ka = excluded.name_ka, description_en = excluded.description_en, description_ka = excluded.description_ka,
  price = excluded.price, category_id = excluded.category_id, model = excluded.model, model_usdz = excluded.model_usdz,
  sort_order = excluded.sort_order, visible = excluded.visible, ar_scale = excluded.ar_scale,
  thumbnail_url = excluded.thumbnail_url, thumb_3d = excluded.thumb_3d;
insert into public.menu_items (name_en, name_ka, description_en, description_ka, price, category_id, model, model_usdz, sort_order, visible, ar_scale, thumbnail_url, thumb_3d) values (
  'Donut', 'დონატი', 'Chocolate donut with banana', 'შოკოლადის დონატი ბანანით', '1,5 ₾', (select id from public.categories where name_en = 'Desserts'), 'https://pub-3c68559de18f4aee94d127e180937bdd.r2.dev/donut_draco.glb', 'https://pub-3c68559de18f4aee94d127e180937bdd.r2.dev/donut.usdz', 4, true, 0.9, 'https://pub-3c68559de18f4aee94d127e180937bdd.r2.dev/donut_poster.webp', true
) on conflict (name_en) do update set
  name_ka = excluded.name_ka, description_en = excluded.description_en, description_ka = excluded.description_ka,
  price = excluded.price, category_id = excluded.category_id, model = excluded.model, model_usdz = excluded.model_usdz,
  sort_order = excluded.sort_order, visible = excluded.visible, ar_scale = excluded.ar_scale,
  thumbnail_url = excluded.thumbnail_url, thumb_3d = excluded.thumb_3d;

notify pgrst, 'reload schema';

-- Verification: should show menu rows, anon-safe analytics insert columns, and no permission errors in the app.
select 'categories' as table_name, count(*) from public.categories
union all select 'menu_items', count(*) from public.menu_items
union all select 'events', count(*) from public.events;
