-- BAOMA real menu import artifact.
-- Source: /home/gagi/baoma_menu_extracted.md from supplied screenshot set 1-15.
-- Review before running: source menu prices/translations need client confirmation, and photo rights/quality should be confirmed before production.
-- Default safety is ROLLBACK. To execute after review, change only the final line from ROLLBACK; to COMMIT;

BEGIN;

do $$
declare
  v_restaurant record;
begin
  select r.id, r.slug, r.name, r.brand_id, b.slug as brand_slug
    into v_restaurant
    from public.restaurants r
    join public.brands b on b.id = r.brand_id
   where r.id = 53
     and r.slug = 'b-main'
     and r.brand_id = 46
     and b.slug = 'b';

  if not found then
    raise exception 'BAOMA identity assertion failed for restaurant %, slug %, brand %, brand slug %', 53, 'b-main', 46, 'b';
  end if;
end $$;

-- If an unused corrupted Featured category exists for BAOMA, repair it only when
-- it has no menu-item references and the intended target category is absent.
do $$
declare
  v_featured_id bigint;
  v_refs integer;
begin
  select id into v_featured_id
    from public.categories
   where restaurant_id = 53
     and lower(name_en) = 'featured'
   limit 1;

  if v_featured_id is not null then
    select count(*) into v_refs
      from public.menu_items
     where restaurant_id = 53
       and category_id = v_featured_id;

    if v_refs = 0 and not exists (
      select 1 from public.categories where restaurant_id = 53 and name_en = 'Breakfast'
    ) then
      update public.categories
         set name_en = 'Breakfast',
             name_ka = 'საუზმე',
             sort_order = 1
       where id = v_featured_id
         and restaurant_id = 53;
    end if;
  end if;
end $$;

with src as (
  select *
  from jsonb_to_recordset($baoma_categories$[
  {
    "name_en": "Breakfast",
    "name_ka": "საუზმე",
    "sort_order": 1
  },
  {
    "name_en": "Salads",
    "name_ka": "სალათები",
    "sort_order": 2
  },
  {
    "name_en": "Soups",
    "name_ka": "სუპები",
    "sort_order": 3
  },
  {
    "name_en": "Georgian Mains",
    "name_ka": "ქართული მთავარი კერძები",
    "sort_order": 4
  },
  {
    "name_en": "Special Dishes & Barbecue",
    "name_ka": "სპეციალური კერძები და მწვადი",
    "sort_order": 5
  },
  {
    "name_en": "Cold Dishes",
    "name_ka": "ცივი კერძები",
    "sort_order": 6
  },
  {
    "name_en": "Pastry & Bread",
    "name_ka": "ცომეული და პური",
    "sort_order": 7
  },
  {
    "name_en": "Pizza",
    "name_ka": "პიცა",
    "sort_order": 8
  },
  {
    "name_en": "Pasta",
    "name_ka": "პასტა",
    "sort_order": 9
  },
  {
    "name_en": "Side Dishes",
    "name_ka": "გარნირები",
    "sort_order": 10
  },
  {
    "name_en": "Sauces",
    "name_ka": "სოუსები",
    "sort_order": 11
  },
  {
    "name_en": "Meze for Two",
    "name_ka": "მენიუ ორ პერსონაზე",
    "sort_order": 12
  },
  {
    "name_en": "Non-Alcoholic Drinks",
    "name_ka": "უალკოჰოლო სასმელები",
    "sort_order": 13
  },
  {
    "name_en": "Coffee & Tea",
    "name_ka": "ყავა და ჩაი",
    "sort_order": 14
  },
  {
    "name_en": "Alcoholic Drinks",
    "name_ka": "ალკოჰოლური სასმელები",
    "sort_order": 15
  },
  {
    "name_en": "Desserts",
    "name_ka": "დესერტები",
    "sort_order": 16
  }
]$baoma_categories$::jsonb)
    as x(name_en text, name_ka text, sort_order integer)
)
insert into public.categories (restaurant_id, name_en, name_ka, sort_order)
select 53, name_en, name_ka, sort_order
from src
on conflict (restaurant_id, name_en) do update
set name_ka = excluded.name_ka,
    sort_order = excluded.sort_order;

with src as (
  select *
  from jsonb_to_recordset($baoma_items$[
  {
    "name_en": "Omelette",
    "name_ka": "ომლეტი",
    "description_en": "",
    "description_ka": "",
    "price": "8 ₾",
    "category_name_en": "Breakfast",
    "model": "",
    "model_usdz": "",
    "sort_order": 1,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Omelette with cheese/sausage",
    "name_ka": "ომლეტი ყველით/სოსისით",
    "description_en": "cheese/sausage",
    "description_ka": "ყველი/სოსისი",
    "price": "12.90 ₾",
    "category_name_en": "Breakfast",
    "model": "",
    "model_usdz": "",
    "sort_order": 2,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Scrambled egg with bacon/cheese",
    "name_ka": "ათქვეფილი კვერცხი ბეკონით/ყველით",
    "description_en": "bacon/cheese",
    "description_ka": "ბეკონი/ყველი",
    "price": "13 ₾",
    "category_name_en": "Breakfast",
    "model": "",
    "model_usdz": "",
    "sort_order": 3,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Bruschetta",
    "name_ka": "ბრუსკეტა",
    "description_en": "",
    "description_ka": "",
    "price": "13 ₾",
    "category_name_en": "Breakfast",
    "model": "",
    "model_usdz": "",
    "sort_order": 4,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Caesar Roll with french fries",
    "name_ka": "ცეზარ როლი კარტოფილი ფრით",
    "description_en": "french fries",
    "description_ka": "კარტოფილი ფრი",
    "price": "15 ₾",
    "category_name_en": "Breakfast",
    "model": "",
    "model_usdz": "",
    "sort_order": 5,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Chicken sandwich with french fries",
    "name_ka": "ქათმის სენდვიჩი კარტოფილი ფრით",
    "description_en": "french fries",
    "description_ka": "კარტოფილი ფრი",
    "price": "12 ₾",
    "category_name_en": "Breakfast",
    "model": "",
    "model_usdz": "",
    "sort_order": 6,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Chicken Burrito with french fries",
    "name_ka": "ქათმის ბურიტო კარტოფილი ფრით",
    "description_en": "french fries",
    "description_ka": "კარტოფილი ფრი",
    "price": "20 ₾",
    "category_name_en": "Breakfast",
    "model": "",
    "model_usdz": "",
    "sort_order": 7,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Pancakes with meat/cheese",
    "name_ka": "ბლინები ხორცით/ყველით",
    "description_en": "meat/cheese",
    "description_ka": "ხორცი/ყველი",
    "price": "9.90 ₾",
    "category_name_en": "Breakfast",
    "model": "",
    "model_usdz": "",
    "sort_order": 8,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Cucumber-tomato salad",
    "name_ka": "კიტრი-პომიდვრის სალათი",
    "description_en": "",
    "description_ka": "",
    "price": "14 ₾",
    "category_name_en": "Salads",
    "model": "",
    "model_usdz": "",
    "sort_order": 9,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Cucumber-tomato salad with walnuts",
    "name_ka": "კიტრი-პომიდვრის სალათი ნიგვზით",
    "description_en": "walnuts",
    "description_ka": "ნიგოზი",
    "price": "16 ₾",
    "category_name_en": "Salads",
    "model": "",
    "model_usdz": "",
    "sort_order": 10,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Greek salad",
    "name_ka": "ბერძნული სალათი",
    "description_en": "",
    "description_ka": "",
    "price": "21 ₾",
    "category_name_en": "Salads",
    "model": "",
    "model_usdz": "",
    "sort_order": 11,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/greek-salad.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Caesar",
    "name_ka": "ცეზარი",
    "description_en": "",
    "description_ka": "",
    "price": "26 ₾",
    "category_name_en": "Salads",
    "model": "",
    "model_usdz": "",
    "sort_order": 12,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Caesar with shrimp",
    "name_ka": "ცეზარი კრევეტებით",
    "description_en": "shrimp",
    "description_ka": "კრევეტები",
    "price": "25 ₾",
    "category_name_en": "Salads",
    "model": "",
    "model_usdz": "",
    "sort_order": 13,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Caesar with salmon",
    "name_ka": "ცეზარი ორაგულით",
    "description_en": "salmon",
    "description_ka": "ორაგული",
    "price": "27 ₾",
    "category_name_en": "Salads",
    "model": "",
    "model_usdz": "",
    "sort_order": 14,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Chicken salad",
    "name_ka": "ქათმის სალათი",
    "description_en": "",
    "description_ka": "",
    "price": "18 ₾",
    "category_name_en": "Salads",
    "model": "",
    "model_usdz": "",
    "sort_order": 15,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Mushroom salad",
    "name_ka": "სოკოს სალათი",
    "description_en": "",
    "description_ka": "",
    "price": "15 ₾",
    "category_name_en": "Salads",
    "model": "",
    "model_usdz": "",
    "sort_order": 16,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Beet salad with tkemali",
    "name_ka": "ჭარხლის სალათი ტყემლით",
    "description_en": "tkemali",
    "description_ka": "ტყემალი",
    "price": "12 ₾",
    "category_name_en": "Salads",
    "model": "",
    "model_usdz": "",
    "sort_order": 17,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Green salad",
    "name_ka": "მწვანე სალათი",
    "description_en": "",
    "description_ka": "",
    "price": "14 ₾",
    "category_name_en": "Salads",
    "model": "",
    "model_usdz": "",
    "sort_order": 18,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Vegetable salad",
    "name_ka": "ბოსტნეულის სალათი",
    "description_en": "",
    "description_ka": "",
    "price": "14 ₾",
    "category_name_en": "Salads",
    "model": "",
    "model_usdz": "",
    "sort_order": 19,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Olives",
    "name_ka": "ზეთისხილი",
    "description_en": "",
    "description_ka": "",
    "price": "9 ₾",
    "category_name_en": "Salads",
    "model": "",
    "model_usdz": "",
    "sort_order": 20,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Steak salad",
    "name_ka": "სტეიკის სალათი",
    "description_en": "",
    "description_ka": "",
    "price": "27 ₾",
    "category_name_en": "Salads",
    "model": "",
    "model_usdz": "",
    "sort_order": 21,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Chikhirtma",
    "name_ka": "ჩიხირთმა",
    "description_en": "chicken fillet, onion, garlic, vinegar, egg",
    "description_ka": "ქათმის ფილე, ხახვი, ნიორი, ძმარი, კვერცხი",
    "price": "14 ₾",
    "category_name_en": "Soups",
    "model": "",
    "model_usdz": "",
    "sort_order": 22,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Mushroom cream-soup",
    "name_ka": "სოკოს კრემ-სუპი",
    "description_en": "",
    "description_ka": "",
    "price": "16 ₾",
    "category_name_en": "Soups",
    "model": "",
    "model_usdz": "",
    "sort_order": 23,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Soup-kharcho",
    "name_ka": "სუპ-ხარჩო",
    "description_en": "beef, onion, rice, tomato, Georgian spices",
    "description_ka": "საქონლის ხორცი, ხახვი, ბრინჯი, პომიდორი, ქართული სუნელები",
    "price": "16 ₾",
    "category_name_en": "Soups",
    "model": "",
    "model_usdz": "",
    "sort_order": 24,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/soup-kharcho.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Fish soup",
    "name_ka": "თევზის სუპი",
    "description_en": "",
    "description_ka": "",
    "price": "16 ₾",
    "category_name_en": "Soups",
    "model": "",
    "model_usdz": "",
    "sort_order": 25,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Tomato cream-soup",
    "name_ka": "პომიდვრის კრემ-სუპი",
    "description_en": "",
    "description_ka": "",
    "price": "12.90 ₾",
    "category_name_en": "Soups",
    "model": "",
    "model_usdz": "",
    "sort_order": 26,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Pumpkin cream-soup",
    "name_ka": "გოგრის კრემ-სუპი",
    "description_en": "",
    "description_ka": "",
    "price": "13.90 ₾",
    "category_name_en": "Soups",
    "model": "",
    "model_usdz": "",
    "sort_order": 27,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/pumpkin-soup.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Vegetables soup",
    "name_ka": "ბოსტნეულის სუპი",
    "description_en": "",
    "description_ka": "",
    "price": "9.90 ₾",
    "category_name_en": "Soups",
    "model": "",
    "model_usdz": "",
    "sort_order": 28,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Tabaka chicken",
    "name_ka": "ტაბაკა",
    "description_en": "",
    "description_ka": "",
    "price": "22 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 29,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/tabaka-chicken.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Shkmeruli",
    "name_ka": "შქმერული",
    "description_en": "fried chicken, garlic sauce, milk, Georgian spices",
    "description_ka": "შემწვარი ქათამი, ნივრის სოუსი, რძე, ქართული სუნელები",
    "price": "30 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 30,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Chick with tkemali",
    "name_ka": "წიწილა ტყემლით",
    "description_en": "",
    "description_ka": "",
    "price": "25 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 31,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Mushrooms on the clay pan",
    "name_ka": "სოკო კეცზე",
    "description_en": "",
    "description_ka": "",
    "price": "14 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 32,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Mushrooms with sulguni on the clay pan",
    "name_ka": "სოკო კეცზე სულგუნით",
    "description_en": "sulguni",
    "description_ka": "სულგუნი",
    "price": "17 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 33,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/mushrooms-sulguni.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Fried sulguni on the clay pan",
    "name_ka": "შემწვარი სულგუნი კეცზე",
    "description_en": "",
    "description_ka": "",
    "price": "16 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 34,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Bean with spices in a pot",
    "name_ka": "ლობიო ქოთანში",
    "description_en": "spices",
    "description_ka": "სუნელები",
    "price": "10 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 35,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Ajapsandal",
    "name_ka": "აჯაფსანდალი",
    "description_en": "",
    "description_ka": "",
    "price": "16 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 36,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Chanakhi with sheep meat",
    "name_ka": "ჩანახი (ცხვრის ხორცით)",
    "description_en": "sheep meat",
    "description_ka": "ცხვრის ხორცი",
    "price": "26 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 37,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Chakapuli (lamb or calf)",
    "name_ka": "ჩაქაფული (ბატკანი ან ხბო)",
    "description_en": "lamb or calf, herbs, tkemali, wine",
    "description_ka": "ბატკანი ან ხბო, მწვანილი, ტყემალი, ღვინო",
    "price": "30 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 38,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Ostry",
    "name_ka": "ოსტრი",
    "description_en": "beef, tomato sauce, onion, Georgian spices",
    "description_ka": "საქონლის ხორცი, ტომატის სოუსი, ხახვი, ქართული სუნელები",
    "price": "26 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 39,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Ojakhuri",
    "name_ka": "ოჯახური",
    "description_en": "pork, fried potatoes, onion, garlic, paprika, Georgian spices",
    "description_ka": "ღორის ხორცი, შემწვარი კარტოფილი, ხახვი, ნიორი, პაპრიკა, ქართული სუნელები",
    "price": "24 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 40,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/ojakhuri.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Chicken chakhokhbili",
    "name_ka": "ქათმის ჩახოხბილი",
    "description_en": "chicken fillet, paprika, tomatoes, onion, herbs, Georgian spices",
    "description_ka": "ქათმის ფილე, პაპრიკა, პომიდორი, ხახვი, მწვანილი, ქართული სუნელები",
    "price": "18 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 41,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Chicken liver on clay pan",
    "name_ka": "ქათმის ღვიძლი კეცზე",
    "description_en": "",
    "description_ka": "",
    "price": "16 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 42,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Beef steak",
    "name_ka": "საქონლის სტეიკი",
    "description_en": "",
    "description_ka": "",
    "price": "35.90 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 43,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Salmon steak",
    "name_ka": "ორაგულის სტეიკი",
    "description_en": "",
    "description_ka": "",
    "price": "35.90 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 44,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Beef stroganoff with potato fries",
    "name_ka": "ბეფსტროგანოვი კარტოფილი ფრით",
    "description_en": "potato fries",
    "description_ka": "კარტოფილი ფრი",
    "price": "34 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 45,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Megrelian kupati",
    "name_ka": "მეგრული კუპატი",
    "description_en": "",
    "description_ka": "",
    "price": "18.90 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 46,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Imeruli kupati",
    "name_ka": "იმერული კუპატი",
    "description_en": "",
    "description_ka": "",
    "price": "17.90 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 47,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Beans in clay pot with mtchadi",
    "name_ka": "ლობიო კეცზე მჭადით",
    "description_en": "mtchadi",
    "description_ka": "მჭადი",
    "price": "14 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 48,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Pelmeni in a pot",
    "name_ka": "პელმენი ქოთანში",
    "description_en": "",
    "description_ka": "",
    "price": "15.90 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 49,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Dumplings with cheese on clay pot",
    "name_ka": "ყველის პელმენი კეცზე",
    "description_en": "cheese",
    "description_ka": "ყველი",
    "price": "16 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 50,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Ojakhuri with veal",
    "name_ka": "ოჯახური ხბოს ხორცით",
    "description_en": "veal",
    "description_ka": "ხბოს ხორცი",
    "price": "23 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 51,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/ojakhuri-veal.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Ojakhuri with pork",
    "name_ka": "ოჯახური ღორის ხორცით",
    "description_en": "pork",
    "description_ka": "ღორის ხორცი",
    "price": "19 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 52,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/ojakhuri-pork.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Roasted sulguni on clay pot",
    "name_ka": "შემწვარი სულგუნი კეცზე",
    "description_en": "sulguni",
    "description_ka": "სულგუნი",
    "price": "13.90 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 53,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Chicken heart and liver on the pan",
    "name_ka": "ქათმის გული და ღვიძლი ტაფაზე",
    "description_en": "chicken heart and liver",
    "description_ka": "ქათმის გული და ღვიძლი",
    "price": "14 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 54,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Tolma",
    "name_ka": "ტოლმა",
    "description_en": "",
    "description_ka": "",
    "price": "18 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 55,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Ghomi",
    "name_ka": "ღომი",
    "description_en": "",
    "description_ka": "",
    "price": "7 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 56,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Ghomi and kharcho",
    "name_ka": "ღომი და ხარჩო",
    "description_en": "",
    "description_ka": "",
    "price": "28 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 57,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Elardji",
    "name_ka": "ელარჯი",
    "description_en": "",
    "description_ka": "",
    "price": "12 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 58,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Trout with pomegranate sauce",
    "name_ka": "კალმახი ბროწეულის სოუსით",
    "description_en": "pomegranate sauce",
    "description_ka": "ბროწეულის სოუსი",
    "price": "18 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 59,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/trout-pomegranate.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Satsivi with chicken",
    "name_ka": "საცივი ქათმით",
    "description_en": "chicken",
    "description_ka": "ქათამი",
    "price": "27 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 60,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/satsivi-chicken.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Veal barbecue",
    "name_ka": "ხბოს მწვადი",
    "description_en": "",
    "description_ka": "",
    "price": "17.90 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 61,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Chicken barbecue",
    "name_ka": "ქათმის მწვადი",
    "description_en": "cucumbers, tomatoes and french fries",
    "description_ka": "კიტრი, პომიდორი და კარტოფილი ფრი",
    "price": "19 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 62,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/chicken-barbecue.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Entrecôte with grilled vegetables",
    "name_ka": "ანტრეკოტი გრილზე შემწვარი ბოსტნეულით",
    "description_en": "grilled vegetables",
    "description_ka": "გრილზე შემწვარი ბოსტნეული",
    "price": "25.90 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 63,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Khinkali",
    "name_ka": "ხინკალი",
    "description_en": "",
    "description_ka": "",
    "price": "1.40 ₾",
    "category_name_en": "Georgian Mains",
    "model": "",
    "model_usdz": "",
    "sort_order": 64,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Assorted barbeque",
    "name_ka": "მწვადის ასორტი",
    "description_en": "cucumbers, tomatoes and french fries",
    "description_ka": "კიტრი, პომიდორი და კარტოფილი ფრი",
    "price": "46 ₾",
    "category_name_en": "Special Dishes & Barbecue",
    "model": "",
    "model_usdz": "",
    "sort_order": 65,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Chicken barbeque",
    "name_ka": "ქათმის მწვადი",
    "description_en": "cucumbers, tomatoes and french fries",
    "description_ka": "კიტრი, პომიდორი და კარტოფილი ფრი",
    "price": "19 ₾",
    "category_name_en": "Special Dishes & Barbecue",
    "model": "",
    "model_usdz": "",
    "sort_order": 66,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Pork barbeque",
    "name_ka": "ღორის მწვადი",
    "description_en": "cucumbers, tomatoes and french fries",
    "description_ka": "კიტრი, პომიდორი და კარტოფილი ფრი",
    "price": "20 ₾",
    "category_name_en": "Special Dishes & Barbecue",
    "model": "",
    "model_usdz": "",
    "sort_order": 67,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/pork-bbq.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Kebab",
    "name_ka": "ქაბაბი",
    "description_en": "cucumbers, tomatoes and french fries",
    "description_ka": "კიტრი, პომიდორი და კარტოფილი ფრი",
    "price": "20 ₾",
    "category_name_en": "Special Dishes & Barbecue",
    "model": "",
    "model_usdz": "",
    "sort_order": 68,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Satsivi with pre-order",
    "name_ka": "საცივი წინასწარი შეკვეთით",
    "description_en": "pre-order",
    "description_ka": "წინასწარი შეკვეთით",
    "price": "45 ₾",
    "category_name_en": "Cold Dishes",
    "model": "",
    "model_usdz": "",
    "sort_order": 69,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Assorted herbs",
    "name_ka": "მწვანილის ასორტი",
    "description_en": "",
    "description_ka": "",
    "price": "8 ₾",
    "category_name_en": "Cold Dishes",
    "model": "",
    "model_usdz": "",
    "sort_order": 70,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Assorted pkhali",
    "name_ka": "ფხალის ასორტი",
    "description_en": "",
    "description_ka": "",
    "price": "23 ₾",
    "category_name_en": "Cold Dishes",
    "model": "",
    "model_usdz": "",
    "sort_order": 71,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Eggplant with walnuts",
    "name_ka": "ბადრიჯანი ნიგვზით",
    "description_en": "walnuts",
    "description_ka": "ნიგოზი",
    "price": "17 ₾",
    "category_name_en": "Cold Dishes",
    "model": "",
    "model_usdz": "",
    "sort_order": 72,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Spinach with walnuts",
    "name_ka": "ისპანახი ნიგვზით",
    "description_en": "walnuts",
    "description_ka": "ნიგოზი",
    "price": "14 ₾",
    "category_name_en": "Cold Dishes",
    "model": "",
    "model_usdz": "",
    "sort_order": 73,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Beet leaves with walnuts",
    "name_ka": "ჭარხლის ფოთოლი ნიგვზით",
    "description_en": "walnuts",
    "description_ka": "ნიგოზი",
    "price": "14 ₾",
    "category_name_en": "Cold Dishes",
    "model": "",
    "model_usdz": "",
    "sort_order": 74,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Cheese Imeruli",
    "name_ka": "იმერული ყველი",
    "description_en": "",
    "description_ka": "",
    "price": "14 ₾",
    "category_name_en": "Cold Dishes",
    "model": "",
    "model_usdz": "",
    "sort_order": 75,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Cheese Sulguni",
    "name_ka": "სულგუნი ყველი",
    "description_en": "",
    "description_ka": "",
    "price": "17 ₾",
    "category_name_en": "Cold Dishes",
    "model": "",
    "model_usdz": "",
    "sort_order": 76,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Cheese assorted",
    "name_ka": "ყველის ასორტი",
    "description_en": "",
    "description_ka": "",
    "price": "24 ₾",
    "category_name_en": "Cold Dishes",
    "model": "",
    "model_usdz": "",
    "sort_order": 77,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Pickled assorted",
    "name_ka": "მწნილის ასორტი",
    "description_en": "",
    "description_ka": "",
    "price": "14 ₾",
    "category_name_en": "Cold Dishes",
    "model": "",
    "model_usdz": "",
    "sort_order": 78,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Appetizer board",
    "name_ka": "საუზმეულის დაფა",
    "description_en": "",
    "description_ka": "",
    "price": "35 ₾",
    "category_name_en": "Cold Dishes",
    "model": "",
    "model_usdz": "",
    "sort_order": 79,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Assorted Georgian cheese",
    "name_ka": "ქართული ყველის ასორტი",
    "description_en": "",
    "description_ka": "",
    "price": "30 ₾",
    "category_name_en": "Cold Dishes",
    "model": "",
    "model_usdz": "",
    "sort_order": 80,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "European assortment of cheese",
    "name_ka": "ევროპული ყველის ასორტი",
    "description_en": "",
    "description_ka": "",
    "price": "36.90 ₾",
    "category_name_en": "Cold Dishes",
    "model": "",
    "model_usdz": "",
    "sort_order": 81,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Khachapuri imeruli",
    "name_ka": "იმერული ხაჭაპური",
    "description_en": "",
    "description_ka": "",
    "price": "15 ₾",
    "category_name_en": "Pastry & Bread",
    "model": "",
    "model_usdz": "",
    "sort_order": 82,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Khachapuri megrelian",
    "name_ka": "მეგრული ხაჭაპური",
    "description_en": "",
    "description_ka": "",
    "price": "18 ₾",
    "category_name_en": "Pastry & Bread",
    "model": "",
    "model_usdz": "",
    "sort_order": 83,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Royal khachapuri",
    "name_ka": "სამეფო ხაჭაპური",
    "description_en": "",
    "description_ka": "",
    "price": "25 ₾",
    "category_name_en": "Pastry & Bread",
    "model": "",
    "model_usdz": "",
    "sort_order": 84,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Khachapuri Adjaruli",
    "name_ka": "აჭარული ხაჭაპური",
    "description_en": "",
    "description_ka": "",
    "price": "12.90 ₾",
    "category_name_en": "Pastry & Bread",
    "model": "",
    "model_usdz": "",
    "sort_order": 85,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/adjaruli-khachapuri.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Lobiani",
    "name_ka": "ლობიანი",
    "description_en": "",
    "description_ka": "",
    "price": "12.90 ₾",
    "category_name_en": "Pastry & Bread",
    "model": "",
    "model_usdz": "",
    "sort_order": 86,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Pancakes with meat (4 pieces)",
    "name_ka": "ბლინები ხორცით (4 ცალი)",
    "description_en": "meat; 4 pieces",
    "description_ka": "ხორცი; 4 ცალი",
    "price": "9.90 ₾",
    "category_name_en": "Pastry & Bread",
    "model": "",
    "model_usdz": "",
    "sort_order": 87,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Pancakes with cheese (4 pieces)",
    "name_ka": "ბლინები ყველით (4 ცალი)",
    "description_en": "cheese; 4 pieces",
    "description_ka": "ყველი; 4 ცალი",
    "price": "9.90 ₾",
    "category_name_en": "Pastry & Bread",
    "model": "",
    "model_usdz": "",
    "sort_order": 88,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Mtchadi",
    "name_ka": "მჭადი",
    "description_en": "",
    "description_ka": "",
    "price": "3.90 ₾",
    "category_name_en": "Pastry & Bread",
    "model": "",
    "model_usdz": "",
    "sort_order": 89,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Chvishtari",
    "name_ka": "ჭვიშტარი",
    "description_en": "",
    "description_ka": "",
    "price": "6.90 ₾",
    "category_name_en": "Pastry & Bread",
    "model": "",
    "model_usdz": "",
    "sort_order": 90,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Bread",
    "name_ka": "პური",
    "description_en": "",
    "description_ka": "",
    "price": "3.90 ₾",
    "category_name_en": "Pastry & Bread",
    "model": "",
    "model_usdz": "",
    "sort_order": 91,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Vegetable Pizza",
    "name_ka": "ბოსტნეულის პიცა",
    "description_en": "",
    "description_ka": "",
    "price": "12 ₾",
    "category_name_en": "Pizza",
    "model": "",
    "model_usdz": "",
    "sort_order": 92,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Pizza Margherita",
    "name_ka": "პიცა მარგარიტა",
    "description_en": "",
    "description_ka": "",
    "price": "14.90 ₾",
    "category_name_en": "Pizza",
    "model": "",
    "model_usdz": "",
    "sort_order": 93,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Pizza pepperoni",
    "name_ka": "პიცა პეპერონი",
    "description_en": "",
    "description_ka": "",
    "price": "18 ₾",
    "category_name_en": "Pizza",
    "model": "",
    "model_usdz": "",
    "sort_order": 94,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Pizza quattro formaggi (4 cheese)",
    "name_ka": "პიცა ოთხი ყველი",
    "description_en": "",
    "description_ka": "",
    "price": "27 ₾",
    "category_name_en": "Pizza",
    "model": "",
    "model_usdz": "",
    "sort_order": 95,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Pizza Mix",
    "name_ka": "პიცა მიქსი",
    "description_en": "",
    "description_ka": "",
    "price": "30 ₾",
    "category_name_en": "Pizza",
    "model": "",
    "model_usdz": "",
    "sort_order": 96,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Carbonara",
    "name_ka": "კარბონარა",
    "description_en": "",
    "description_ka": "",
    "price": "17.90 ₾",
    "category_name_en": "Pasta",
    "model": "",
    "model_usdz": "",
    "sort_order": 97,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Pasta quattro formaggi",
    "name_ka": "პასტა ოთხი ყველი",
    "description_en": "",
    "description_ka": "",
    "price": "17.90 ₾",
    "category_name_en": "Pasta",
    "model": "",
    "model_usdz": "",
    "sort_order": 98,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "French fries",
    "name_ka": "კარტოფილი ფრი",
    "description_en": "",
    "description_ka": "",
    "price": "8 ₾",
    "category_name_en": "Side Dishes",
    "model": "",
    "model_usdz": "",
    "sort_order": 99,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Mexican potatoes",
    "name_ka": "მექსიკური კარტოფილი",
    "description_en": "",
    "description_ka": "",
    "price": "12 ₾",
    "category_name_en": "Side Dishes",
    "model": "",
    "model_usdz": "",
    "sort_order": 100,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Puree",
    "name_ka": "პიურე",
    "description_en": "",
    "description_ka": "",
    "price": "5 ₾",
    "category_name_en": "Side Dishes",
    "model": "",
    "model_usdz": "",
    "sort_order": 101,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Rice with vegetables",
    "name_ka": "ბრინჯი ბოსტნეულით",
    "description_en": "",
    "description_ka": "",
    "price": "10 ₾",
    "category_name_en": "Side Dishes",
    "model": "",
    "model_usdz": "",
    "sort_order": 102,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Grilled vegetables",
    "name_ka": "გრილზე შემწვარი ბოსტნეული",
    "description_en": "",
    "description_ka": "",
    "price": "12.90 ₾",
    "category_name_en": "Side Dishes",
    "model": "",
    "model_usdz": "",
    "sort_order": 103,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/grilled-vegetables.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Georgian crisps",
    "name_ka": "ქართული ჩიფსი",
    "description_en": "",
    "description_ka": "",
    "price": "10 ₾",
    "category_name_en": "Side Dishes",
    "model": "",
    "model_usdz": "",
    "sort_order": 104,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Ketchup",
    "name_ka": "კეტჩუპი",
    "description_en": "",
    "description_ka": "",
    "price": "3 ₾",
    "category_name_en": "Sauces",
    "model": "",
    "model_usdz": "",
    "sort_order": 105,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Tkemali",
    "name_ka": "ტყემალი",
    "description_en": "",
    "description_ka": "",
    "price": "3 ₾",
    "category_name_en": "Sauces",
    "model": "",
    "model_usdz": "",
    "sort_order": 106,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Bullace sauce",
    "name_ka": "ტყემლის სოუსი",
    "description_en": "",
    "description_ka": "",
    "price": "3 ₾",
    "category_name_en": "Sauces",
    "model": "",
    "model_usdz": "",
    "sort_order": 107,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Tomato sauce",
    "name_ka": "ტომატის სოუსი",
    "description_en": "",
    "description_ka": "",
    "price": "3 ₾",
    "category_name_en": "Sauces",
    "model": "",
    "model_usdz": "",
    "sort_order": 108,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Quattro formaggi sauce",
    "name_ka": "ოთხი ყველის სოუსი",
    "description_en": "",
    "description_ka": "",
    "price": "9 ₾",
    "category_name_en": "Sauces",
    "model": "",
    "model_usdz": "",
    "sort_order": 109,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Mexican sauce",
    "name_ka": "მექსიკური სოუსი",
    "description_en": "",
    "description_ka": "",
    "price": "3 ₾",
    "category_name_en": "Sauces",
    "model": "",
    "model_usdz": "",
    "sort_order": 110,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Green adjika",
    "name_ka": "მწვანე აჯიკა",
    "description_en": "",
    "description_ka": "",
    "price": "3 ₾",
    "category_name_en": "Sauces",
    "model": "",
    "model_usdz": "",
    "sort_order": 111,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Red adjika",
    "name_ka": "წითელი აჯიკა",
    "description_en": "",
    "description_ka": "",
    "price": "3 ₾",
    "category_name_en": "Sauces",
    "model": "",
    "model_usdz": "",
    "sort_order": 112,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Georgian national meze for two persons",
    "name_ka": "ქართული ნაციონალური მენიუ ორ პერსონაზე",
    "description_en": "1. Cucumber and tomato salad; 2. Spinach with walnuts; 3. Beet leaf with walnuts; 4. Eggplant with walnuts; 5. Pickled cabbage; 6. Stewed beef (Ostri); 7. Chakapuli (beef or lamb); 8. Chicken chakhokhbili; 9. Boiled bean with spices; 10. French fries",
    "description_ka": "1. კიტრისა და პომიდვრის სალათა; 2. ისპანახი ნიგვზით; 3. ჭარხლის ფოთოლი ნიგვზით; 4. ბადრიჯანი ნიგვზით; 5. მჟავე კომბოსტო; 6. ძროხის ჩაშუშული (ოსტრი); 7. ჩაქაფული (ხბო ან ბატკანი); 8. ქათმის ჩახოხბილი; 9. ლობიო; 10. კარტოფილი ფრი",
    "price": "115 ₾",
    "category_name_en": "Meze for Two",
    "model": "",
    "model_usdz": "",
    "sort_order": 113,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Water",
    "name_ka": "წყალი",
    "description_en": "",
    "description_ka": "",
    "price": "3 ₾",
    "category_name_en": "Non-Alcoholic Drinks",
    "model": "",
    "model_usdz": "",
    "sort_order": 114,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Borjomi",
    "name_ka": "ბორჯომი",
    "description_en": "",
    "description_ka": "",
    "price": "6 ₾",
    "category_name_en": "Non-Alcoholic Drinks",
    "model": "",
    "model_usdz": "",
    "sort_order": 115,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Nabeglavi",
    "name_ka": "ნაბეღლავი",
    "description_en": "",
    "description_ka": "",
    "price": "6 ₾",
    "category_name_en": "Non-Alcoholic Drinks",
    "model": "",
    "model_usdz": "",
    "sort_order": 116,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Coca-Cola",
    "name_ka": "კოკა-კოლა",
    "description_en": "",
    "description_ka": "",
    "price": "7 ₾",
    "category_name_en": "Non-Alcoholic Drinks",
    "model": "",
    "model_usdz": "",
    "sort_order": 117,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Sparkling lemonade",
    "name_ka": "ნატახტარის ლიმონათი",
    "description_en": "",
    "description_ka": "",
    "price": "5 ₾",
    "category_name_en": "Non-Alcoholic Drinks",
    "model": "",
    "model_usdz": "",
    "sort_order": 118,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Fresh juice",
    "name_ka": "ნატურალური წვენი",
    "description_en": "",
    "description_ka": "",
    "price": "20 ₾",
    "category_name_en": "Non-Alcoholic Drinks",
    "model": "",
    "model_usdz": "",
    "sort_order": 119,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Tea",
    "name_ka": "ჩაი",
    "description_en": "",
    "description_ka": "",
    "price": "5 ₾",
    "category_name_en": "Coffee & Tea",
    "model": "",
    "model_usdz": "",
    "sort_order": 120,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Turkish coffee",
    "name_ka": "თურქული ყავა",
    "description_en": "",
    "description_ka": "",
    "price": "6 ₾",
    "category_name_en": "Coffee & Tea",
    "model": "",
    "model_usdz": "",
    "sort_order": 121,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Instant coffee",
    "name_ka": "ხსნადი ყავა",
    "description_en": "",
    "description_ka": "",
    "price": "6 ₾",
    "category_name_en": "Coffee & Tea",
    "model": "",
    "model_usdz": "",
    "sort_order": 122,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Espresso",
    "name_ka": "ესპრესო",
    "description_en": "",
    "description_ka": "",
    "price": "8 ₾",
    "category_name_en": "Coffee & Tea",
    "model": "",
    "model_usdz": "",
    "sort_order": 123,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Americano",
    "name_ka": "ამერიკანო",
    "description_en": "",
    "description_ka": "",
    "price": "8 ₾",
    "category_name_en": "Coffee & Tea",
    "model": "",
    "model_usdz": "",
    "sort_order": 124,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Cappuccino",
    "name_ka": "კაპუჩინო",
    "description_en": "",
    "description_ka": "",
    "price": "9 ₾",
    "category_name_en": "Coffee & Tea",
    "model": "",
    "model_usdz": "",
    "sort_order": 125,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Iced coffee",
    "name_ka": "ცივი ყავა",
    "description_en": "",
    "description_ka": "",
    "price": "8 ₾",
    "category_name_en": "Coffee & Tea",
    "model": "",
    "model_usdz": "",
    "sort_order": 126,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Iced coffee with ice cream",
    "name_ka": "ცივი ყავა ნაყინით",
    "description_en": "ice cream",
    "description_ka": "ნაყინი",
    "price": "10 ₾",
    "category_name_en": "Coffee & Tea",
    "model": "",
    "model_usdz": "",
    "sort_order": 127,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "White dry homemade wine",
    "name_ka": "თეთრი მშრალი",
    "description_en": "homemade wine",
    "description_ka": "სახლის ღვინო",
    "price": "8 ₾",
    "category_name_en": "Alcoholic Drinks",
    "model": "",
    "model_usdz": "",
    "sort_order": 128,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": [
      {
        "en": "glass",
        "ka": "ჭიქა",
        "price": "8 ₾",
        "source": [
          8
        ]
      },
      {
        "en": "0.5 L",
        "ka": "0.5 ლ",
        "price": "30 ₾",
        "source": [
          8
        ]
      },
      {
        "en": "1 L",
        "ka": "1 ლ",
        "price": "45 ₾",
        "source": [
          8
        ]
      },
      {
        "en": "1.5 L",
        "ka": "1.5 ლ",
        "price": "60 ₾",
        "source": [
          8
        ]
      }
    ]
  },
  {
    "name_en": "Red dry homemade wine",
    "name_ka": "წითელი მშრალი",
    "description_en": "homemade wine",
    "description_ka": "სახლის ღვინო",
    "price": "8 ₾",
    "category_name_en": "Alcoholic Drinks",
    "model": "",
    "model_usdz": "",
    "sort_order": 129,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": [
      {
        "en": "glass",
        "ka": "ჭიქა",
        "price": "8 ₾",
        "source": [
          8
        ]
      },
      {
        "en": "0.5 L",
        "ka": "0.5 ლ",
        "price": "30 ₾",
        "source": [
          8
        ]
      },
      {
        "en": "1 L",
        "ka": "1 ლ",
        "price": "45 ₾",
        "source": [
          8
        ]
      },
      {
        "en": "1.5 L",
        "ka": "1.5 ლ",
        "price": "60 ₾",
        "source": [
          8
        ]
      }
    ]
  },
  {
    "name_en": "Semi-sweet red homemade wine",
    "name_ka": "წითელი ნახევრად ტკბილი",
    "description_en": "homemade wine",
    "description_ka": "სახლის ღვინო",
    "price": "9 ₾",
    "category_name_en": "Alcoholic Drinks",
    "model": "",
    "model_usdz": "",
    "sort_order": 130,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": [
      {
        "en": "glass",
        "ka": "ჭიქა",
        "price": "9 ₾",
        "source": [
          8
        ]
      },
      {
        "en": "0.5 L",
        "ka": "0.5 ლ",
        "price": "35 ₾",
        "source": [
          8
        ]
      },
      {
        "en": "1 L",
        "ka": "1 ლ",
        "price": "50 ₾",
        "source": [
          8
        ]
      },
      {
        "en": "1.5 L",
        "ka": "1.5 ლ",
        "price": "70 ₾",
        "source": [
          8
        ]
      }
    ]
  },
  {
    "name_en": "Vodka — 50 gr",
    "name_ka": "არაყი — 50 გრ",
    "description_en": "50 gr",
    "description_ka": "50 გრ",
    "price": "6 ₾",
    "category_name_en": "Alcoholic Drinks",
    "model": "",
    "model_usdz": "",
    "sort_order": 131,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Chacha — 50 gr",
    "name_ka": "ჭაჭა — 50 გრ",
    "description_en": "50 gr",
    "description_ka": "50 გრ",
    "price": "6 ₾",
    "category_name_en": "Alcoholic Drinks",
    "model": "",
    "model_usdz": "",
    "sort_order": 132,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Cognac — 50 gr",
    "name_ka": "კონიაკი — 50 გრ",
    "description_en": "50 gr",
    "description_ka": "50 გრ",
    "price": "8 ₾",
    "category_name_en": "Alcoholic Drinks",
    "model": "",
    "model_usdz": "",
    "sort_order": 133,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Natakhtari beer",
    "name_ka": "ნატახტარი",
    "description_en": "0.5 L",
    "description_ka": "0.5 ლ",
    "price": "8 ₾",
    "category_name_en": "Alcoholic Drinks",
    "model": "",
    "model_usdz": "",
    "sort_order": 134,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": [
      {
        "en": "draft 0.5 L",
        "ka": "ჩამოსასხმელი 0.5 ლ",
        "price": "8 ₾",
        "source": [
          8
        ]
      },
      {
        "en": "bottled 0.5 L",
        "ka": "ბოთლის 0.5 ლ",
        "price": "8 ₾",
        "source": [
          8
        ]
      }
    ]
  },
  {
    "name_en": "Ice-cream",
    "name_ka": "ნაყინი",
    "description_en": "",
    "description_ka": "",
    "price": "7 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 135,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Fruit assorted",
    "name_ka": "ხილის ასორტი",
    "description_en": "",
    "description_ka": "",
    "price": "24 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 136,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Pan cakes",
    "name_ka": "ბლინები",
    "description_en": "",
    "description_ka": "",
    "price": "10 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 137,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Cake",
    "name_ka": "ნამცხვარი",
    "description_en": "",
    "description_ka": "",
    "price": "7 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 138,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Churchkhela",
    "name_ka": "ჩურჩხელა",
    "description_en": "",
    "description_ka": "",
    "price": "7 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 139,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Fruit tray",
    "name_ka": "ხილის დაფა",
    "description_en": "",
    "description_ka": "",
    "price": "35 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 140,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Churchkhela and nuts board",
    "name_ka": "ჩურჩხელისა და თხილეულის დაფა",
    "description_en": "",
    "description_ka": "",
    "price": "19.90 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 141,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Brownie with ice-cream",
    "name_ka": "ბრაუნი ნაყინით",
    "description_en": "",
    "description_ka": "",
    "price": "12.90 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 142,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Cheesecake",
    "name_ka": "ჩიზქეიქი",
    "description_en": "",
    "description_ka": "",
    "price": "12 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 143,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Crepe with banana and chocolate",
    "name_ka": "კრეპი ბანანით და შოკოლადით",
    "description_en": "",
    "description_ka": "",
    "price": "9 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 144,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Ice-cream with fruit",
    "name_ka": "ნაყინი ხილით",
    "description_en": "",
    "description_ka": "",
    "price": "9.90 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 145,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Ice-cream with nuts and chocolate",
    "name_ka": "ნაყინი თხილით და შოკოლადით",
    "description_en": "",
    "description_ka": "",
    "price": "9.90 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 146,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Peanuts",
    "name_ka": "არაქისი",
    "description_en": "",
    "description_ka": "",
    "price": "5.90 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 147,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": true,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Cherry",
    "name_ka": "ალუბალი",
    "description_en": "Cherry Confit; Mint Cream; Milk Chocolate Mousse with Tonka Beans",
    "description_ka": "ალუბლის კონფი; პიტნის კრემი; რძიანი შოკოლადის მუსი ტონკას მარცვლებით",
    "price": "18 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 148,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/dessert-cherry.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Apple",
    "name_ka": "ვაშლი",
    "description_en": "Caramel Sponge Cake; With Thin Beans; Crispy Caramel Layer; Apple Compote",
    "description_ka": "კარამელის ბისკვიტი; თინ ბინსით; ხრაშუნა კარამელის ფენა; ვაშლის კომპოტი",
    "price": "18 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 149,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/dessert-apple.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Heart",
    "name_ka": "გული",
    "description_en": "Chocolate Sponge Cake; Chocolate Ganache with Hazelnuts; Bavarian Mousse",
    "description_ka": "შოკოლადის ბისკვიტი; შოკოლადის განაში თხილით; ბავარიული მუსი",
    "price": "18 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 150,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/dessert-heart.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Lemon",
    "name_ka": "ლიმონი",
    "description_en": "Lemon Cream; Lemon Ganache; Lemon Biscuit; Lemon Mousse",
    "description_ka": "ლიმონის კრემი; ლიმონის განაში; ლიმონის ბისკვიტი; ლიმონის მუსი",
    "price": "18 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 151,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/dessert-lemon.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Pearl",
    "name_ka": "მარგალიტი",
    "description_en": "Lime sponge cake; Strawberry confit with lime; Meringue mousse with strawberries",
    "description_ka": "ლაიმის ბისკვიტი; მარწყვის კონფი ლაიმით; მერენგის მუსი მარწყვით",
    "price": "18 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 152,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/dessert-pearl.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Origami",
    "name_ka": "ორიგამი",
    "description_en": "Coconut Mousse & biscuit; Pineapple Compote; Pina Colada Ganache; Crunchy Layer",
    "description_ka": "ქოქოსის მუსი და ბისკვიტი; ანანასის კომპოტი; პინა კოლადას განაში; ხრაშუნა ფენა",
    "price": "18 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 153,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/dessert-origami.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Spiral",
    "name_ka": "სპირალი",
    "description_en": "Pistachio Dacquoise Biscuit; Raspberry Compote; Raspberry cream; Pistachio Mousse",
    "description_ka": "ფსტის დაკუაზის ბისკვიტი; ჟოლოს კომპოტი; ჟოლოს კრემი; ფსტის მუსი",
    "price": "18 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 154,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/dessert-spiral.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  },
  {
    "name_en": "Duna",
    "name_ka": "დუნა",
    "description_en": "Apricot; Passion Fruit; White Chocolate; Cream; Almond Flour; Flour; Egg",
    "description_ka": "გარგარი; პასიფლორა; თეთრი შოკოლადი; კრემი; ნუშის ფქვილი; ფქვილი; კვერცხი",
    "price": "18 ₾",
    "category_name_en": "Desserts",
    "model": "",
    "model_usdz": "",
    "sort_order": 155,
    "visible": true,
    "ar_scale": 1,
    "thumbnail_url": "https://restaurant-ar.pages.dev/img/baoma/dishes/dessert-duna.webp",
    "thumb_3d": false,
    "is_3d": false,
    "text_only": false,
    "addons": [],
    "variants": []
  }
]$baoma_items$::jsonb)
    as x(
      name_en text,
      name_ka text,
      description_en text,
      description_ka text,
      price text,
      category_name_en text,
      model text,
      model_usdz text,
      sort_order integer,
      visible boolean,
      ar_scale numeric,
      thumbnail_url text,
      thumb_3d boolean,
      is_3d boolean,
      text_only boolean,
      addons jsonb,
      variants jsonb
    )
)
insert into public.menu_items (
  restaurant_id, name_en, name_ka, description_en, description_ka, price,
  category_id, model, model_usdz, sort_order, visible, ar_scale,
  thumbnail_url, thumb_3d, is_3d, text_only, addons, variants
)
select
  53,
  src.name_en,
  src.name_ka,
  src.description_en,
  src.description_ka,
  src.price,
  (
    select c.id
      from public.categories c
     where c.restaurant_id = 53
       and c.name_en = src.category_name_en
  ),
  src.model,
  src.model_usdz,
  src.sort_order,
  src.visible,
  src.ar_scale,
  src.thumbnail_url,
  src.thumb_3d,
  src.is_3d,
  src.text_only,
  coalesce(src.addons, '[]'::jsonb),
  coalesce(src.variants, '[]'::jsonb)
from src
on conflict (restaurant_id, name_en) do update
set name_ka = excluded.name_ka,
    description_en = excluded.description_en,
    description_ka = excluded.description_ka,
    price = excluded.price,
    category_id = excluded.category_id,
    model = excluded.model,
    model_usdz = excluded.model_usdz,
    sort_order = excluded.sort_order,
    visible = excluded.visible,
    ar_scale = excluded.ar_scale,
    thumbnail_url = excluded.thumbnail_url,
    thumb_3d = excluded.thumb_3d,
    is_3d = excluded.is_3d,
    text_only = excluded.text_only,
    addons = excluded.addons,
    variants = excluded.variants;

with src as (
  select *
  from jsonb_to_recordset($baoma_theme$[
  {
    "key": "phone_layout",
    "value": "twin"
  },
  {
    "key": "drink_categories",
    "value": "[\"Non-Alcoholic Drinks\",\"Coffee & Tea\",\"Alcoholic Drinks\"]"
  },
  {
    "key": "template_key",
    "value": "baoma"
  },
  {
    "key": "default_theme",
    "value": "day"
  },
  {
    "key": "site_name",
    "value": "BAOMA"
  },
  {
    "key": "site_name_ka",
    "value": "ბაომა"
  },
  {
    "key": "hero_kicker",
    "value": "Georgian restaurant in Tbilisi"
  },
  {
    "key": "hero_kicker_ka",
    "value": "ქართული რესტორანი თბილისში"
  },
  {
    "key": "hero_copy",
    "value": "A warm Georgian table with floral interiors, rose tones, and a calm rooftop mood."
  },
  {
    "key": "hero_copy_ka",
    "value": "თბილი ქართული სუფრა ყვავილოვანი ინტერიერით, ვარდისფერი ტონებით და მშვიდი ტერასის განწყობით."
  },
  {
    "key": "hero_cta",
    "value": "Explore Menu"
  },
  {
    "key": "hero_cta_ka",
    "value": "მენიუს ნახვა"
  },
  {
    "key": "info_kicker",
    "value": "Visit BAOMA"
  },
  {
    "key": "info_kicker_ka",
    "value": "ეწვიეთ ბაომას"
  },
  {
    "key": "info_title",
    "value": "11 Erekle II Street"
  },
  {
    "key": "info_title_ka",
    "value": "ერეკლე II-ის ქუჩა 11"
  },
  {
    "key": "info_text",
    "value": "Georgian cuisine in the heart of Tbilisi. Follow the official Instagram or get directions to the restaurant."
  },
  {
    "key": "info_text_ka",
    "value": "ქართული სამზარეულო თბილისის გულში. იხილეთ ოფიციალური Instagram ან მიიღეთ მიმართულება რესტორნამდე."
  },
  {
    "key": "info_directions_label",
    "value": "Get Directions"
  },
  {
    "key": "info_directions_label_ka",
    "value": "მიმართულება"
  },
  {
    "key": "info_directions_url",
    "value": "https://www.google.com/maps/search/?api=1&query=11%20Erekle%20II%20Street%2C%20Tbilisi%2C%20Georgia"
  },
  {
    "key": "info_instagram_label",
    "value": "@restaurant.baoma"
  },
  {
    "key": "info_instagram_label_ka",
    "value": "@restaurant.baoma"
  },
  {
    "key": "info_instagram_url",
    "value": "https://www.instagram.com/restaurant.baoma/"
  }
]$baoma_theme$::jsonb)
    as x(key text, value text)
)
insert into public.theme_config (restaurant_id, key, value)
select 53, key, value
from src
on conflict (restaurant_id, key) do update
set value = excluded.value,
    updated_at = now();

notify pgrst, 'reload schema';

-- Validation queries: these should be inspected before switching to COMMIT.
select 'baoma_category_count' as check_name, count(*) as value
  from public.categories
 where restaurant_id = 53;

select 'baoma_visible_menu_item_count' as check_name, count(*) as value
  from public.menu_items
 where restaurant_id = 53
   and visible = true;

select 'baoma_photo_item_count' as check_name, count(*) as value
  from public.menu_items
 where restaurant_id = 53
   and visible = true
   and coalesce(thumbnail_url, '') <> '';

select restaurant_id, name_en, count(*) as duplicate_count
  from public.menu_items
 where restaurant_id = 53
 group by restaurant_id, name_en
having count(*) > 1;

select mi.id, mi.name_en, mi.category_id
  from public.menu_items mi
  left join public.categories c
    on c.id = mi.category_id
 where mi.restaurant_id = 53
   and (mi.category_id is null or c.id is null);

select mi.id, mi.name_en, mi.category_id, c.restaurant_id as category_restaurant_id
  from public.menu_items mi
  join public.categories c on c.id = mi.category_id
 where mi.restaurant_id = 53
   and c.restaurant_id <> 53;

select id, name_en
  from public.menu_items
 where restaurant_id = 53
   and visible = true
   and coalesce(is_3d, false) = true;

select id, name_en
  from public.menu_items
 where restaurant_id = 53
   and visible = true
   and text_only = true
   and coalesce(thumbnail_url, '') <> '';

-- COMMIT switch: replace the next line with COMMIT; after validation and approval.
ROLLBACK;
