-- Food & Market targeted catalogue photo refresh (Unicode source).
-- Generated by scripts/generate-food-market-catalogue.mjs; rollback-first and rollback-only.
-- Updates media flags by the existing unique database-facing name_en; it never inserts or deletes menu rows.
BEGIN;

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM public.restaurants r JOIN public.brands b ON b.id = r.brand_id WHERE r.id = 73 AND r.slug = 'food-market-main' AND r.name = 'Food & Market' AND r.brand_id = 67 AND b.id = 67 AND b.slug = 'food-market' AND b.name = 'Food & Market') THEN
    RAISE EXCEPTION 'Food & Market identity assertion failed';
  END IF;
  IF (SELECT count(*) FROM public.menu_items WHERE restaurant_id = 73 AND visible IS TRUE) <> 228 THEN
    RAISE EXCEPTION 'expected exactly 228 current visible Food & Market items';
  END IF;
  IF EXISTS (SELECT 1 FROM public.menu_items WHERE restaurant_id = 73 AND visible IS TRUE GROUP BY name_en HAVING count(*) <> 1) THEN
    RAISE EXCEPTION 'database-facing name_en must be unique';
  END IF;
  IF (SELECT count(*) FROM public.menu_items WHERE restaurant_id = 73 AND is_3d IS TRUE) <> 3 OR EXISTS (
    SELECT 1 FROM (VALUES (1383), (1385), (1421)) protected(id)
    LEFT JOIN public.menu_items m ON m.restaurant_id = 73 AND m.id = protected.id
    WHERE m.id IS NULL OR m.visible IS NOT TRUE OR m.is_3d IS NOT TRUE OR COALESCE(m.model, '') = '' OR COALESCE(m.model_usdz, '') = ''
  ) THEN RAISE EXCEPTION 'Food & Market protected 3D rows mismatch'; END IF;
END $$;

CREATE TEMP TABLE _fm_photo_refresh (name_en text PRIMARY KEY, thumbnail_url text NOT NULL, protected_3d boolean NOT NULL) ON COMMIT DROP;
INSERT INTO _fm_photo_refresh VALUES
  ('MARGHERITA', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-pizza-margherita-be994ec3.webp', false),
  ('PEPPERONI', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-pizza-pepperoni-8d5dbf53.webp', false),
  ('4 CHEESE', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-pizza-4-cheese-36db3ff4.webp', false),
  ('PROSCIUTTO', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-pizza-prosciutto-a9bd932a.webp', false),
  (U&'CHEF\2019S PIZZA', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-pizza-chef-s-pizza-79e31a3c.webp', false),
  ('VEGETARIAN', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-pizza-vegetarian-c4a788ef.webp', false),
  ('BLACK TRUFFLE PIZZA', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-pizza-black-truffle-pizza-c33f8865.webp', false),
  ('CHICKEN BURGER', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-burger-chicken-burger-7876e33f.webp', false),
  ('CHEF BURGER', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-burger-chef-burger-38541c00.webp', false),
  ('SMASHED BURGER', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-burger-smashed-burger-ebd145b4.webp', false),
  ('STEAK SANDWICH', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-burger-steak-sandwich-5b19c603.webp', false),
  ('SALMON PASTA', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-pasta-salmon-pasta-f9c1979a.webp', false),
  ('PENNE ARRABIATA', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-pasta-penne-arrabiata-a4fe893f.webp', false),
  ('PENNE BOLOGNESE', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-pasta-penne-bolognese-b2f25680.webp', false),
  ('SPAGHETTI CARBONARA', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-pasta-spaghetti-carbonara-ea8790a9.webp', false),
  ('MUSHROOM & TRUFFLE FUSILLONI', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-pasta-mushroom-truffle-fusilloni-6846af91.webp', false),
  ('DIP MIXES', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-appetizer-dip-mixes-3dc84e38.webp', false),
  ('PULLED BBQ PORK TACO', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-appetizer-pulled-bbq-pork-taco-40ac841b.webp', false),
  ('PULLED BEEF TACO', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-appetizer-pulled-beef-taco-ea5b3809.webp', false),
  ('HUMMUS WITH GREEN SALAD AND PITA', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-appetizer-hummus-with-green-salad-and-pita-09899e43.webp', false),
  ('FRENCH FRIES WITH TRUFFLE SAUCE', '', false),
  ('FRENCH FRIES', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-appetizer-french-fries-e51c291a.webp', false),
  ('CAESAR SALAD with CHICKEN', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-salads-caesar-salad-with-chicken-83c5e750.webp', false),
  ('BURRATA SALAD', 'https://restaurant-ar.pages.dev/assets/food-market/items/burrata-salad.webp', true),
  ('Kakhetian Cucumber & Tomato salad', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-salads-kakhetian-cucumber-tomato-salad-88a72917.webp', false),
  ('Cucumber & Tomato salad with Walnut', '', false),
  ('SHRIMP SALAD', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-salads-shrimp-salad-e95e835a.webp', false),
  ('BEEF SOUP, RICE NOODLES', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-soups-beef-soup-rice-noodles-3467d582.webp', false),
  ('CHIKHIRTMA WITH SMOKED SULGUNI', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-soups-chikhirtma-with-smoked-sulguni-5bcc338d.webp', false),
  ('3 MUSHROOMS CREAM SOUP', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-soups-3-mushrooms-cream-soup-36a0b582.webp', false),
  ('PUMPKIN CREAM SOUP, CROSTINI', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-soups-pumpkin-cream-soup-crostini-f811cc9d.webp', false),
  ('CHICKEN STICKS WITH SESAME', '', false),
  ('CHEESE STICKS IN TOMATO SAUCE', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-croquettes-cheese-sticks-in-tomato-sauce-2236666f.webp', false),
  ('LOBIO BALLS WITH HAM IN JONJOLI SAUCE', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-croquettes-lobio-balls-with-ham-in-jonjoli-sauce-f3a95e7f.webp', false),
  ('CHICKEN BALLS IN SHKMERULI SAUCE', 'https://restaurant-ar.pages.dev/assets/food-market/items/chicken-balls.webp', true),
  ('ELARJI BALLS WITH KUPATI IN BAJHE SAUCE', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-croquettes-elarji-balls-with-kupati-in-bajhe-sauce-19004b06.webp', false),
  ('IMERETIAN KHACHAPURI', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-dough-imeretian-khachapuri-d9a7147a.webp', false),
  ('ADJARIAN KHACHAPURI', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-dough-adjarian-khachapuri-ce148d4c.webp', false),
  ('MEGRELIAN KHACHAPURI', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-dough-megrelian-khachapuri-807f1cac.webp', false),
  ('CHICKEN SCHNITZEL', '', false),
  ('SALMON WITH SPINACH', '', false),
  ('GRILLED LEMON CHICKEN, PARMESAN, SUN DRIED TOMATO', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/georgian-main-grilled-lemon-chicken-parmesan-sun-dried-tomato-64932864.webp', false),
  ('Stir Fried Cashewnut', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-stir-fried-stir-fried-cashewnut-c4f23bd9.webp', false),
  ('Stir Fried Broccoli with Shrimp', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-stir-fried-stir-fried-broccoli-with-shrimp-78852514.webp', false),
  ('Thai Style Fried Rice', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-fried-rice-thai-style-fried-rice-0c36ef82.webp', false),
  ('Sriracha Fried Rice', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-fried-rice-sriracha-fried-rice-c15b028b.webp', false),
  ('Chicken Donburi', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-fried-rice-chicken-donburi-921bcc63.webp', false),
  ('Rice with Grilled Chicken & Satay Sauce', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-fried-rice-rice-with-grilled-chicken-satay-sauce-3f9526f7.webp', false),
  ('Grilled chicken with curry rice', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-fried-rice-grilled-chicken-with-curry-rice-318b2413.webp', false),
  ('Grilled Chicken Salad', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-salads-grilled-chicken-salad-7e9e6541.webp', false),
  ('Crispy Chicken Salad', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-salads-crispy-chicken-salad-ec4bad53.webp', false),
  ('Crispy Shrimp with Tamarind Sauce', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-appetizer-crispy-shrimp-with-tamarind-sauce-f6ce1da9.webp', false),
  ('Kimchi', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-appetizer-kimchi-3b825892.webp', false),
  ('Panang Curry', '', false),
  ('Massaman Curry', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-curry-massaman-curry-2b971818.webp', false),
  ('Grilled Chicken Red Hot Curry', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-curry-grilled-chicken-red-hot-curry-385723bc.webp', false),
  ('Green Curry', '', false),
  ('Yellow Curry', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-curry-yellow-curry-90b3043c.webp', false),
  ('Stir fried Noodles Sriracha Sauce', '', false),
  ('Stir fried Noodles Soy Sauce', '', false),
  ('Stir fried Glass Noodles', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-noodles-stir-fried-glass-noodles-579bf1e0.webp', false),
  ('Pad Si Euw', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-noodles-pad-si-euw-abb9ba89.webp', false),
  ('Pad Thai Noodles', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-noodles-pad-thai-noodles-51db39cd.webp', false),
  ('Tom Yum Seafood Clear Soup', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-soup-tom-yum-seafood-clear-soup-abc1f01d.webp', false),
  ('Thai Noodles Black Soup', '', false),
  ('Thai Noodle Soup with Chicken Shreded', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-soup-thai-noodle-soup-with-chicken-shreded-3e4a168d.webp', false),
  ('Tom Yum', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-soup-tom-yum-831de21f.webp', false),
  ('Tom Kha', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-soup-tom-kha-e7903c0f.webp', false),
  ('Tom Yum Ramen with Shrimp', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-soup-tom-yum-ramen-with-shrimp-fe461bf0.webp', false),
  ('Pho with Beef', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-soup-pho-with-beef-0227bc69.webp', false),
  ('Salmon Sashimi', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-sashimi-salmon-c4df884a.webp', false),
  ('Tuna Sashimi', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-sashimi-tuna-cb0ac111.webp', false),
  ('Chef', '', false),
  ('Salmon Nigiri', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-nigiri-salmon-5d4b1700.webp', false),
  ('Tuna Nigiri', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-nigiri-tuna-12b59aae.webp', false),
  ('Salmon Onigiri', '', false),
  ('Shrimp', '', false),
  ('Kappa Maki', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-maki-kappa-maki-dadcd67a.webp', false),
  ('Shake Maki', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-maki-shake-maki-9d8c01bd.webp', false),
  ('Ebi Maki', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-maki-ebi-maki-ae7748fb.webp', false),
  ('Unagi Philadelphia', 'https://pub-b253d60df14c4c1f94bada002fa59596.r2.dev/food-market-main/1787819264838_sushi.webp', true),
  ('Crab Uramaki', '', false),
  ('Unagi Crispy Roll', '', false),
  ('Spicy Salmon', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-uramaki-roll-spicy-salmon-a2638534.webp', false),
  ('California', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-uramaki-roll-california-abc72fa1.webp', false),
  ('Dragon', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-uramaki-roll-dragon-f3d3cdbd.webp', false),
  ('Spicy Tuna', '', false),
  ('Philadelphia', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-uramaki-roll-philadelphia-95728346.webp', false),
  ('Unagi', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-uramaki-roll-unagi-1d173319.webp', false),
  ('Tropical Shrimp', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-uramaki-roll-tropical-shrimp-21e2858b.webp', false),
  ('Royal Philadelphia', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-uramaki-roll-royal-philadelphia-433ab334.webp', false),
  ('Spicy Philadelphia', '', false),
  ('Veggie Futomaki', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-futomaki-veggie-futomaki-30f9c0ba.webp', false),
  ('Tuna Futomaki', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-futomaki-tuna-futomaki-aeb46b98.webp', false),
  ('Salmon Futomaki', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/asian-futomaki-salmon-futomaki-11eb978a.webp', false),
  ('Salmon Poke Bowl', '', false),
  ('Tuna Poke Bowl', '', false),
  ('Shrimp Poke Bowl', '', false),
  ('Faustino VII Blanco 2024, Bodegas Spain', '', false),
  ('Lumina Pinot Grigio delle Venezie DOC 2024, Ruffino Italy', '', false),
  (U&'Riesling \201Cvom Roten Schiefer\201D 2021, Germany', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-classic-riesling-vom-roten-schiefer-2021-germany-56c77f33.webp', false),
  ('Hey French Bianco Veneto, Multivintage Pasqua Italy', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-classic-hey-french-bianco-veneto-multivintage-pasqua-italy-917eee9b.webp', false),
  ('Graves Blanc, Reserve, Bordeaux 2022, Mouton Cadet France', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-classic-graves-blanc-reserve-bordeaux-2022-mouton-cadet-france-30d4c529.webp', false),
  ('Tsinandali, Naberauli', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-classic-tsinandali-naberauli-7870c78b.webp', false),
  ('Mtsvane, Kardanakhi 1888', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-classic-mtsvane-kardanakhi-1888-b57233a7.webp', false),
  ('Tsiskari, Eclipse, Tkatsiteli 2021', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-classic-tsiskari-eclipse-tkatsiteli-2021-bd56bbd6.webp', false),
  ('Mtsvane, Shakriani Estate', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-classic-mtsvane-shakriani-estate-84d9452a.webp', false),
  ('Chinuri-Goruli Mtsvane, Gulodrava', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-classic-chinuri-goruli-mtsvane-gulodrava-c11e6efc.webp', false),
  ('Atenuri, Gulodrava', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-classic-atenuri-gulodrava-b77b1ca0.webp', false),
  ('Tsolikauri, Anemo', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-dry-qvevri-tsolikauri-anemo-4b2d206d.webp', false),
  ('Goruli Mtsvane, Zedashe', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-dry-qvevri-goruli-mtsvane-zedashe-11d8b041.webp', false),
  ('Mtsvane, Rtvelisi', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-dry-qvevri-mtsvane-rtvelisi-4e99f40a.webp', false),
  ('Rkatsiteli, Vardiashvili', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-dry-qvevri-rkatsiteli-vardiashvili-9466a7c1.webp', false),
  ('Khikhvi, Pirveli Winery', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-dry-qvevri-khikhvi-pirveli-winery-23e642f3.webp', false),
  ('Kisi, Shakriani Estate', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-dry-qvevri-kisi-shakriani-estate-2b6afe3b.webp', false),
  ('Tvishi, Naberauli', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-semi-sweet-tvishi-naberauli-862391d6.webp', false),
  ('Gviani Mosavali, Barbale', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-white-semi-sweet-gviani-mosavali-barbale-77df6f4c.webp', false),
  ('Faustino VII Tempranillo 2023, Bodegas Spain', '', false),
  ('10 Meses 2023, Portia Spain', '', false),
  ('1877 Chianti DOCG, Ruffino Italy', '', false),
  ('Primitivo di Manduria DOC 2024, Tenute Orestiadi Italy', '', false),
  ('Saint-Emilion, Reserve Bordeaux 2020, Mouton Cadet France', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-dry-classic-saint-emilion-reserve-bordeaux-2020-mouton-cadet-france-63c85df4.webp', false),
  (U&'Lui\2019, Cabernet Sauvignon Veneto 2018, Pasqua Italy', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-dry-classic-lui-cabernet-sauvignon-veneto-2018-pasqua-italy-c143271c.webp', false),
  ('Rosso Veneto IGT 2021, Pasqua Italy', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-dry-classic-rosso-veneto-igt-2021-pasqua-italy-7acd829b.webp', false),
  ('Saperavi Esabi, Eclipse', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-dry-classic-saperavi-esabi-eclipse-d9a0fe79.webp', false),
  ('Saperavi Dzelshavi, Royal Khvanchkara', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-dry-classic-saperavi-dzelshavi-royal-khvanchkara-78ec5af0.webp', false),
  ('Asuretuli, Marbano', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-dry-classic-asuretuli-marbano-86566d29.webp', false),
  ('Saperavi, Shakriani Estate (Classic)', '', false),
  ('Otskhanuri Sapere, Gulodrava', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-dry-classic-otskhanuri-sapere-gulodrava-2770acdb.webp', false),
  ('Saperavi, Gulodrava', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-dry-classic-saperavi-gulodrava-03a0ed47.webp', false),
  ('Saperavi, Rtvelisi (Bottle)', '', false),
  ('Saperavi, Anemo', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-dry-qvevri-saperavi-anemo-d8e5da1a.webp', false),
  ('Shavkapito, Zedashe', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-dry-qvevri-shavkapito-zedashe-328197f7.webp', false),
  ('Asuretuli, Zedashe', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-dry-qvevri-asuretuli-zedashe-d112ca86.webp', false),
  ('Saperavi, Shakriani Estate (Qvevri)', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-dry-qvevri-saperavi-shakriani-estate-97ad5aa8.webp', false),
  ('Kindzmarauli, Rtvelisi', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-semi-sweet-kindzmarauli-rtvelisi-bbfe7615.webp', false),
  ('Khvanchkara, Royal Khvanchkara', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-semi-sweet-khvanchkara-royal-khvanchkara-4c981895.webp', false),
  ('Usakhelauri, Royal Racha', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-red-semi-sweet-usakhelauri-royal-racha-25901b52.webp', false),
  ('11 Minutes, Rose Trevenezie 2023, Pasqua Italy', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-rose-11-minutes-rose-trevenezie-2023-pasqua-italy-80984c98.webp', false),
  ('Saperavi Rose, Chelti', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-rose-saperavi-rose-chelti-84a37f82.webp', false),
  ('Shavkapito Rose, Amosa', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-rose-shavkapito-rose-amosa-9a40490c.webp', false),
  ('Usakhelauri Rose, Naberauli', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-rose-usakhelauri-rose-naberauli-25bdae92.webp', false),
  ('Askaneli Brut', '', false),
  ('Bodegas Faustino Cava Brut', '', false),
  ('Soffio Prosecco DOC Millesimato 2025', '', false),
  ('Faustino Cava Brut, Bodegas', '', false),
  ('Pinot Grigio, Ruffino', '', false),
  ('Primitivo di Manduria', '', false),
  ('Cava Brut, Campo Viejo', '', false),
  ('Monastrell 2021, Bodegas Carchelo', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-wine-by-the-glass-monastrell-2021-bodegas-carchelo-da23ff9c.webp', false),
  ('EYA Verdejo 2023, Bodegas Carchelo', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-wine-by-the-glass-eya-verdejo-2023-bodegas-carchelo-3e1759e2.webp', false),
  ('Tsolikauri Kisi, Rtvelisi', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-wine-by-the-glass-tsolikauri-kisi-rtvelisi-282d2b4f.webp', false),
  ('Tsinandali, Chelti', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-wine-by-the-glass-tsinandali-chelti-2665ea36.webp', false),
  ('Tvishi, Rtvelisi', 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/drinks-wine-by-the-glass-tvishi-rtvelisi-1f5994c4.webp', false),
  ('Saperavi, Rtvelisi (Glass)', '', false),
  ('Borjomi Sparkling Water', '', false),
  ('Bakuriani Mineral Water', '', false),
  ('Limonati by Borjomi', '', false),
  ('Coca-Cola', '', false),
  ('Coca-Cola Zero', '', false),
  ('Kombucha', '', false),
  ('Juice', '', false),
  ('Fresh', '', false),
  ('Homemade Lemonade with Mint and Lemon', '', false),
  ('Homemade Lemonade Citrus', '', false),
  ('Homemade Lemonade Berries', '', false),
  ('Laghidze Waters', '', false),
  ('Espresso', '', false),
  ('Americano', '', false),
  ('Turkish Coffee', '', false),
  ('Cappuccino', '', false),
  ('Black Tea', '', false),
  ('Green Tea', '', false),
  ('Fruit Tea', '', false),
  ('Double Espresso', '', false),
  ('Latte', '', false),
  ('Mint & Bekondara Tea', '', false),
  ('Ice Coffee', '', false),
  ('Ice Coffee with Ice Cream', '', false),
  ('Super Bock', '', false),
  ('Qarva', '', false),
  ('Corona', '', false),
  ('Stella', '', false),
  ('Lowenbrau', '', false),
  ('Leffe', '', false),
  ('Absolut', '', false),
  ('Grey Goose', '', false),
  ('Stolichnaya', '', false),
  ('Chef Chacha', '', false),
  ('Tanqueray London Dry', '', false),
  ('Tanqueray 10', '', false),
  (U&'Hendrick\2019s', '', false),
  ('Don Julio Blanco', '', false),
  ('Don Julio Reposado', '', false),
  ('Martini', '', false),
  ('Aperol', '', false),
  (U&'J\00E4germeister', '', false),
  ('Captain Morgan', '', false),
  ('Zacapa 23y', '', false),
  ('Baileys', '', false),
  ('Johnnie Walker Red Label', '', false),
  ('Johnnie Walker Black Label', '', false),
  ('Singleton 12y', '', false),
  ('Singleton 15y', '', false),
  ('Talisker 10y', '', false),
  ('Bulleit Rye', '', false),
  ('Tullamore', '', false),
  ('Kilbeggan', '', false),
  ('Askaneli 3y', '', false),
  ('Askaneli 6y', '', false),
  ('Askaneli VSOP', '', false),
  (U&'R\00E9my Martin VSOP', '', false),
  ('Figleton', '', false),
  ('Orchard Boulevardier', '', false),
  ('Espresso Martini', '', false),
  ('Lovely Weekend', '', false),
  ('Miss Sunshine', '', false),
  ('Moscow Mule', '', false),
  ('Rum Berries', '', false),
  ('Cucumber and Basil Smash', '', false),
  ('Negroni', '', false),
  ('Aperol Spritz', '', false),
  ('Gin Tonic', '', false),
  ('Mohito', '', false),
  ('Cuba Libre', '', false),
  ('Long Island', '', false),
  ('Elder Johnny', '', false),
  ('Smashing Walk', '', false);

DO $$
BEGIN
  IF (SELECT count(*) FROM _fm_photo_refresh) <> 228 THEN RAISE EXCEPTION 'expected 228 refresh mappings'; END IF;
  IF (SELECT count(*) FROM _fm_photo_refresh WHERE thumbnail_url LIKE 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/%' AND protected_3d IS FALSE) <> 116 THEN RAISE EXCEPTION 'expected 116 catalogue photo mappings'; END IF;
  IF (SELECT count(*) FROM _fm_photo_refresh WHERE protected_3d) <> 3 THEN RAISE EXCEPTION 'expected 3 protected mappings'; END IF;
  IF EXISTS (
    (SELECT name_en FROM _fm_photo_refresh EXCEPT SELECT name_en FROM public.menu_items WHERE restaurant_id = 73 AND visible IS TRUE)
    UNION ALL
    (SELECT name_en FROM public.menu_items WHERE restaurant_id = 73 AND visible IS TRUE EXCEPT SELECT name_en FROM _fm_photo_refresh)
  ) THEN RAISE EXCEPTION 'live item names differ from generated 228-item catalogue'; END IF;
END $$;

CREATE TEMP TABLE _fm_protected_media AS
SELECT id, thumbnail_url, model, model_usdz, is_3d, ar_scale, thumb_3d
FROM public.menu_items WHERE restaurant_id = 73 AND id IN (1383, 1385, 1421);

UPDATE public.menu_items m
SET thumbnail_url = src.thumbnail_url,
    text_only = (src.thumbnail_url = '')
FROM _fm_photo_refresh src
WHERE m.restaurant_id = 73 AND m.visible IS TRUE AND m.name_en = src.name_en AND src.protected_3d IS FALSE;

DO $$
BEGIN
  IF (SELECT count(*) FROM public.menu_items WHERE restaurant_id = 73 AND visible IS TRUE AND thumbnail_url LIKE 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/%') <> 116 THEN RAISE EXCEPTION 'expected 116 catalogue URLs'; END IF;
  IF EXISTS (SELECT 1 FROM public.menu_items m JOIN _fm_photo_refresh src ON src.name_en = m.name_en WHERE m.restaurant_id = 73 AND m.visible IS TRUE AND src.protected_3d IS FALSE AND (m.thumbnail_url IS DISTINCT FROM src.thumbnail_url OR m.text_only IS DISTINCT FROM (src.thumbnail_url = ''))) THEN RAISE EXCEPTION 'photo refresh mismatch'; END IF;
  IF EXISTS (SELECT 1 FROM _fm_protected_media p LEFT JOIN public.menu_items m ON m.restaurant_id = 73 AND m.id = p.id WHERE m.id IS NULL OR m.thumbnail_url IS DISTINCT FROM p.thumbnail_url OR m.model IS DISTINCT FROM p.model OR m.model_usdz IS DISTINCT FROM p.model_usdz OR m.is_3d IS DISTINCT FROM p.is_3d OR m.ar_scale IS DISTINCT FROM p.ar_scale OR m.thumb_3d IS DISTINCT FROM p.thumb_3d) THEN RAISE EXCEPTION 'protected 3D media changed'; END IF;
  IF (SELECT count(*) FROM public.menu_items WHERE restaurant_id = 73 AND visible IS TRUE AND is_3d IS TRUE) <> 3 THEN RAISE EXCEPTION 'expected exactly 3 models'; END IF;
  IF EXISTS (SELECT 1 FROM public.menu_items WHERE restaurant_id = 73 AND visible IS TRUE GROUP BY name_en HAVING count(*) > 1) THEN RAISE EXCEPTION 'duplicate database-facing name_en'; END IF;
  IF EXISTS (SELECT 1 FROM public.menu_items m LEFT JOIN public.categories c ON c.id = m.category_id AND c.restaurant_id = m.restaurant_id WHERE m.restaurant_id = 73 AND m.visible IS TRUE AND c.id IS NULL) THEN RAISE EXCEPTION 'orphan/cross-tenant category'; END IF;
END $$;

SELECT count(*) AS items, count(*) FILTER (WHERE is_3d) AS models, count(*) FILTER (WHERE thumbnail_url LIKE 'https://restaurant-ar.pages.dev/assets/food-market/catalogue/%') AS catalogue_urls FROM public.menu_items WHERE restaurant_id = 73 AND visible IS TRUE;
ROLLBACK;
