-- Name: 2026-06-29_multitenant_platform_foundation
-- Purpose: Move BetaReal toward the shared multi-tenant platform model without
-- breaking the existing Burger Lions live tenant.
-- Run after 2026-06-28_burger_lions_live_schema.sql.

create table if not exists public.brands (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text not null,
  plan text not null default 'ar_menu',
  logo_url text not null default '',
  primary_color text not null default '',
  secondary_color text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint brands_slug_key unique (slug),
  constraint brands_plan_check check (plan in ('ar_menu', 'full', 'premium')),
  constraint brands_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create table if not exists public.restaurants (
  id bigint generated by default as identity primary key,
  brand_id bigint not null references public.brands(id) on delete cascade,
  name text not null,
  slug text not null,
  custom_domain text,
  status text not null default 'active',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint restaurants_slug_key unique (slug),
  constraint restaurants_custom_domain_key unique (custom_domain),
  constraint restaurants_status_check check (status in ('active', 'inactive')),
  constraint restaurants_slug_format check (slug ~ '^[a-z0-9]+(?:-[a-z0-9]+)*$')
);

create table if not exists public.brand_users (
  brand_id bigint not null references public.brands(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'brand_owner',
  created_at timestamptz not null default now(),
  primary key (brand_id, user_id),
  constraint brand_users_role_check check (role in ('brand_owner'))
);

create table if not exists public.restaurant_users (
  restaurant_id bigint not null references public.restaurants(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  role text not null default 'branch_staff',
  created_at timestamptz not null default now(),
  primary key (restaurant_id, user_id),
  constraint restaurant_users_role_check check (role in ('branch_staff'))
);

insert into public.brands (name, slug, plan)
values ('Burger Lions', 'burger-lions', 'premium')
on conflict (slug) do update set
  name = excluded.name,
  plan = case
    when public.brands.plan in ('ar_menu', 'full', 'premium') then public.brands.plan
    else excluded.plan
  end,
  updated_at = now();

insert into public.restaurants (brand_id, name, slug, status)
select id, 'Burger Lions Main', 'burger-lions-main', 'active'
from public.brands
where slug = 'burger-lions'
on conflict (slug) do update set
  brand_id = excluded.brand_id,
  name = excluded.name,
  status = excluded.status,
  updated_at = now();

alter table public.categories add column if not exists restaurant_id bigint references public.restaurants(id) on delete cascade;
alter table public.menu_items add column if not exists restaurant_id bigint references public.restaurants(id) on delete cascade;
alter table public.theme_config add column if not exists restaurant_id bigint references public.restaurants(id) on delete cascade;
alter table public.events add column if not exists brand_id bigint references public.brands(id) on delete set null;
alter table public.events add column if not exists restaurant_id bigint references public.restaurants(id) on delete set null;

update public.categories
set restaurant_id = (select id from public.restaurants where slug = 'burger-lions-main')
where restaurant_id is null;

update public.menu_items
set restaurant_id = (select id from public.restaurants where slug = 'burger-lions-main')
where restaurant_id is null;

update public.theme_config
set restaurant_id = (select id from public.restaurants where slug = 'burger-lions-main')
where restaurant_id is null;

update public.events
set
  restaurant_id = coalesce(restaurant_id, (select id from public.restaurants where slug = 'burger-lions-main')),
  brand_id = coalesce(brand_id, (select brand_id from public.restaurants where slug = 'burger-lions-main'))
where restaurant_id is null or brand_id is null;

alter table public.categories alter column restaurant_id set not null;
alter table public.menu_items alter column restaurant_id set not null;
alter table public.theme_config alter column restaurant_id set not null;

do $$
begin
  if exists (
    select 1 from information_schema.table_constraints
    where constraint_schema = 'public' and table_name = 'categories' and constraint_name = 'categories_name_en_key'
  ) then
    alter table public.categories drop constraint categories_name_en_key;
  end if;

  if exists (
    select 1 from information_schema.table_constraints
    where constraint_schema = 'public' and table_name = 'menu_items' and constraint_name = 'menu_items_name_en_key'
  ) then
    alter table public.menu_items drop constraint menu_items_name_en_key;
  end if;

  if exists (
    select 1 from information_schema.table_constraints
    where constraint_schema = 'public' and table_name = 'theme_config' and constraint_name = 'theme_config_pkey'
  ) then
    alter table public.theme_config drop constraint theme_config_pkey;
  end if;
end $$;

drop index if exists public.categories_name_en_key;
drop index if exists public.menu_items_name_en_key;
create unique index if not exists categories_restaurant_name_en_key on public.categories (restaurant_id, name_en);
create unique index if not exists menu_items_restaurant_name_en_key on public.menu_items (restaurant_id, name_en);

do $$
begin
  if not exists (
    select 1 from information_schema.table_constraints
    where constraint_schema = 'public' and table_name = 'theme_config' and constraint_name = 'theme_config_pkey'
  ) then
    alter table public.theme_config add constraint theme_config_pkey primary key (restaurant_id, key);
  end if;
end $$;

create index if not exists restaurants_brand_id_idx on public.restaurants (brand_id);
create index if not exists restaurants_slug_idx on public.restaurants (slug);
create index if not exists restaurants_custom_domain_idx on public.restaurants (custom_domain) where custom_domain is not null;
create index if not exists categories_restaurant_id_idx on public.categories (restaurant_id, sort_order);
create index if not exists menu_items_restaurant_id_idx on public.menu_items (restaurant_id, sort_order);
create index if not exists menu_items_category_id_idx on public.menu_items (category_id);
create index if not exists events_restaurant_created_at_idx on public.events (restaurant_id, created_at desc);
create index if not exists events_brand_created_at_idx on public.events (brand_id, created_at desc);
create index if not exists brand_users_user_id_idx on public.brand_users (user_id);
create index if not exists restaurant_users_user_id_idx on public.restaurant_users (user_id);

create or replace function public.current_app_role()
returns text
language sql
stable
as $$
  select coalesce(
    nullif(auth.jwt() -> 'app_metadata' ->> 'role', ''),
    nullif(auth.jwt() -> 'user_metadata' ->> 'role', '')
  )
$$;

create or replace function public.is_super_admin()
returns boolean
language sql
stable
as $$
  select public.current_app_role() in ('super_admin', 'creator', 'dev')
$$;

create or replace function public.can_access_brand(target_brand_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_super_admin()
    or exists (
      select 1 from public.brand_users bu
      where bu.brand_id = target_brand_id
        and bu.user_id = auth.uid()
    )
    or exists (
      select 1
      from public.restaurant_users ru
      join public.restaurants r on r.id = ru.restaurant_id
      where r.brand_id = target_brand_id
        and ru.user_id = auth.uid()
    )
$$;

create or replace function public.can_manage_brand(target_brand_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_super_admin()
    or exists (
      select 1 from public.brand_users bu
      where bu.brand_id = target_brand_id
        and bu.user_id = auth.uid()
        and bu.role = 'brand_owner'
    )
$$;

create or replace function public.can_access_restaurant(target_restaurant_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_super_admin()
    or exists (
      select 1
      from public.restaurants r
      join public.brand_users bu on bu.brand_id = r.brand_id
      where r.id = target_restaurant_id
        and bu.user_id = auth.uid()
    )
    or exists (
      select 1 from public.restaurant_users ru
      where ru.restaurant_id = target_restaurant_id
        and ru.user_id = auth.uid()
    )
$$;

create or replace function public.can_manage_restaurant(target_restaurant_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select public.is_super_admin()
    or exists (
      select 1
      from public.restaurants r
      join public.brand_users bu on bu.brand_id = r.brand_id
      where r.id = target_restaurant_id
        and bu.user_id = auth.uid()
        and bu.role = 'brand_owner'
    )
    or exists (
      select 1 from public.restaurant_users ru
      where ru.restaurant_id = target_restaurant_id
        and ru.user_id = auth.uid()
        and ru.role = 'branch_staff'
    )
$$;

create or replace function public.fill_event_tenant()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if new.restaurant_id is null then
    select id into new.restaurant_id
    from public.restaurants
    where slug = 'burger-lions-main'
    limit 1;
  end if;

  if new.brand_id is null and new.restaurant_id is not null then
    select brand_id into new.brand_id
    from public.restaurants
    where id = new.restaurant_id;
  end if;

  return new;
end $$;

drop trigger if exists events_fill_event_tenant on public.events;
create trigger events_fill_event_tenant
before insert on public.events
for each row execute function public.fill_event_tenant();

create or replace function public.create_platform_tenant(
  p_brand_name text,
  p_brand_slug text,
  p_restaurant_name text,
  p_restaurant_slug text,
  p_plan text default 'ar_menu',
  p_primary_color text default '',
  p_secondary_color text default '',
  p_create_starter_category boolean default true
)
returns table (
  brand_id bigint,
  brand_name text,
  brand_slug text,
  plan text,
  restaurant_id bigint,
  restaurant_name text,
  restaurant_slug text
)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_brand_id bigint;
  v_restaurant_id bigint;
begin
  if not public.is_super_admin() then
    raise exception 'Only super admins can create tenants' using errcode = '42501';
  end if;

  if coalesce(trim(p_brand_name), '') = '' or coalesce(trim(p_restaurant_name), '') = '' then
    raise exception 'Brand name and first branch name are required' using errcode = '22023';
  end if;

  if p_brand_slug !~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' or p_restaurant_slug !~ '^[a-z0-9]+(?:-[a-z0-9]+)*$' then
    raise exception 'Slugs must use lowercase letters, numbers, and hyphens' using errcode = '22023';
  end if;

  if p_plan not in ('ar_menu', 'full', 'premium') then
    raise exception 'Plan must be ar_menu, full, or premium' using errcode = '22023';
  end if;

  insert into public.brands (name, slug, plan, primary_color, secondary_color)
  values (trim(p_brand_name), p_brand_slug, p_plan, coalesce(p_primary_color, ''), coalesce(p_secondary_color, ''))
  returning id into v_brand_id;

  insert into public.restaurants (brand_id, name, slug, status)
  values (v_brand_id, trim(p_restaurant_name), p_restaurant_slug, 'active')
  returning id into v_restaurant_id;

  if p_create_starter_category then
    insert into public.categories (restaurant_id, name_en, name_ka, sort_order)
    values (v_restaurant_id, 'Featured', 'რჩეული', 1);
  end if;

  insert into public.theme_config (restaurant_id, key, value)
  values
    (v_restaurant_id, 'site_name', trim(p_brand_name)),
    (v_restaurant_id, 'site_name_ka', trim(p_brand_name))
  on conflict on constraint theme_config_pkey do update set value = excluded.value;

  if coalesce(p_primary_color, '') <> '' then
    insert into public.theme_config (restaurant_id, key, value)
    values (v_restaurant_id, 'night_accent', p_primary_color)
    on conflict on constraint theme_config_pkey do update set value = excluded.value;
  end if;

  if coalesce(p_secondary_color, '') <> '' then
    insert into public.theme_config (restaurant_id, key, value)
    values (v_restaurant_id, 'day_accent', p_secondary_color)
    on conflict on constraint theme_config_pkey do update set value = excluded.value;
  end if;

  return query
  select
    b.id,
    b.name,
    b.slug,
    b.plan,
    r.id,
    r.name,
    r.slug
  from public.brands b
  join public.restaurants r on r.brand_id = b.id
  where b.id = v_brand_id and r.id = v_restaurant_id;
end $$;

alter table public.brands enable row level security;
alter table public.restaurants enable row level security;
alter table public.brand_users enable row level security;
alter table public.restaurant_users enable row level security;

drop policy if exists brands_public_read_active on public.brands;
create policy brands_public_read_active on public.brands
for select using (true);

drop policy if exists brands_super_admin_write on public.brands;
create policy brands_super_admin_write on public.brands
for all using (public.is_super_admin()) with check (public.is_super_admin());

drop policy if exists restaurants_public_read_active on public.restaurants;
create policy restaurants_public_read_active on public.restaurants
for select using (status = 'active' or public.can_access_restaurant(id));

drop policy if exists restaurants_admin_write on public.restaurants;
create policy restaurants_admin_write on public.restaurants
for all using (public.can_manage_brand(brand_id)) with check (public.can_manage_brand(brand_id));

drop policy if exists brand_users_member_read on public.brand_users;
create policy brand_users_member_read on public.brand_users
for select using (public.is_super_admin() or user_id = auth.uid() or public.can_manage_brand(brand_id));

drop policy if exists brand_users_super_admin_write on public.brand_users;
create policy brand_users_super_admin_write on public.brand_users
for all using (public.is_super_admin()) with check (public.is_super_admin());

drop policy if exists restaurant_users_member_read on public.restaurant_users;
create policy restaurant_users_member_read on public.restaurant_users
for select using (public.is_super_admin() or user_id = auth.uid() or public.can_manage_restaurant(restaurant_id));

drop policy if exists restaurant_users_super_admin_write on public.restaurant_users;
create policy restaurant_users_super_admin_write on public.restaurant_users
for all using (public.is_super_admin()) with check (public.is_super_admin());

drop policy if exists categories_public_read on public.categories;
create policy categories_public_read on public.categories
for select using (
  exists (
    select 1 from public.restaurants r
    where r.id = restaurant_id and r.status = 'active'
  )
);

drop policy if exists categories_auth_write on public.categories;
create policy categories_auth_write on public.categories
for all using (public.can_manage_restaurant(restaurant_id)) with check (public.can_manage_restaurant(restaurant_id));

drop policy if exists menu_items_public_read_visible on public.menu_items;
create policy menu_items_public_read_visible on public.menu_items
for select using (
  visible
  and exists (
    select 1 from public.restaurants r
    where r.id = restaurant_id and r.status = 'active'
  )
);

drop policy if exists menu_items_auth_write on public.menu_items;
create policy menu_items_auth_write on public.menu_items
for all using (public.can_manage_restaurant(restaurant_id)) with check (public.can_manage_restaurant(restaurant_id));

drop policy if exists theme_config_public_read on public.theme_config;
create policy theme_config_public_read on public.theme_config
for select using (
  exists (
    select 1 from public.restaurants r
    where r.id = restaurant_id and r.status = 'active'
  )
);

drop policy if exists theme_config_auth_write on public.theme_config;
create policy theme_config_auth_write on public.theme_config
for all using (public.can_manage_restaurant(restaurant_id)) with check (public.can_manage_restaurant(restaurant_id));

drop policy if exists events_public_insert on public.events;
create policy events_public_insert on public.events
for insert with check (
  restaurant_id is not null
  and brand_id is not null
  and exists (
    select 1 from public.restaurants r
    where r.id = restaurant_id
      and r.brand_id = brand_id
      and r.status = 'active'
  )
);

drop policy if exists events_auth_read on public.events;
create policy events_auth_read on public.events
for select using (public.can_access_brand(brand_id) or public.can_access_restaurant(restaurant_id));

grant select on public.brands, public.restaurants to anon, authenticated;
grant select on public.brand_users, public.restaurant_users to authenticated;
grant select, insert, update, delete on public.brands, public.restaurants, public.brand_users, public.restaurant_users to authenticated;
grant select on public.categories, public.menu_items, public.theme_config to anon, authenticated;
grant insert on public.events to anon, authenticated;
grant select on public.events to authenticated;
grant select, insert, update, delete on public.categories, public.menu_items, public.theme_config to authenticated;
grant execute on function public.current_app_role() to anon, authenticated;
grant execute on function public.is_super_admin() to anon, authenticated;
grant execute on function public.can_access_brand(bigint) to authenticated;
grant execute on function public.can_manage_brand(bigint) to authenticated;
grant execute on function public.can_access_restaurant(bigint) to authenticated;
grant execute on function public.can_manage_restaurant(bigint) to authenticated;
grant execute on function public.create_platform_tenant(text, text, text, text, text, text, text, boolean) to authenticated;

notify pgrst, 'reload schema';

select
  b.slug as brand_slug,
  b.plan,
  r.slug as restaurant_slug,
  (select count(*) from public.categories c where c.restaurant_id = r.id) as categories,
  (select count(*) from public.menu_items mi where mi.restaurant_id = r.id) as menu_items
from public.brands b
join public.restaurants r on r.brand_id = b.id
where b.slug = 'burger-lions';
